# Generated by Django 5.2.9 on 2026-03-10 01:56

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academic", "0019_alter_studentdocument_document_number_and_more"),
        ("core", "0008_job"),
    ]

    operations = [
        migrations.CreateModel(
            name="HostelBlock",
            fields=[
                (
                    "block_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("mixed", "Mixed"),
                        ],
                        default="mixed",
                        max_length=10,
                    ),
                ),
                ("warden_name", models.CharField(blank=True, max_length=100)),
                ("warden_phone", models.CharField(blank=True, max_length=20)),
                ("total_rooms", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hostel_blocks",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="HostelRoom",
            fields=[
                (
                    "room_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("room_number", models.CharField(max_length=20)),
                (
                    "room_type",
                    models.CharField(
                        choices=[
                            ("single", "Single"),
                            ("double", "Double"),
                            ("dormitory", "Dormitory"),
                        ],
                        default="double",
                        max_length=20,
                    ),
                ),
                ("capacity", models.PositiveSmallIntegerField(default=2)),
                (
                    "monthly_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("floor", models.PositiveSmallIntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "block",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rooms",
                        to="hostel.hostelblock",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hostel_rooms",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["block", "floor", "room_number"],
                "unique_together": {("block", "room_number")},
            },
        ),
        migrations.CreateModel(
            name="HostelAllotment",
            fields=[
                (
                    "allotment_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("check_in_date", models.DateField()),
                ("check_out_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("remarks", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hostel_allotments",
                        to="academic.student",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hostel_allotments",
                        to="core.tenant",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allotments",
                        to="hostel.hostelroom",
                    ),
                ),
            ],
            options={
                "ordering": ["-check_in_date"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "is_active"],
                        name="hostel_allot_tenant_active_idx",
                    )
                ],
            },
        ),
    ]
