# Generated by Django 5.2.9 on 2026-02-08 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_initial"),
        ("notifications", "0005_alter_notification_recipient"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("subject_template", models.CharField(max_length=255)),
                ("body_template", models.TextField()),
                (
                    "type",
                    models.CharField(
                        choices=[("email", "Email"), ("sms", "SMS"), ("app", "In-App")],
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_templates",
                        to="core.tenant",
                    ),
                ),
            ],
        ),
    ]
