[phases.setup]
aptPkgs = ["...", "libcairo2-dev", "pkg-config", "python3-pip", "python3-venv"]

[variables]
C_INCLUDE_PATH = "/usr/include"
CPLUS_INCLUDE_PATH = "/usr/include"

[phases.install]
cmds = ["python3 -m pip install --upgrade pip setuptools && python3 -m pip install -r requirements.txt"]

[start]
cmd = "cd backend && python3 manage.py migrate_schemas --shared --noinput && python3 manage.py migrate_schemas --schema=public --noinput && python3 manage.py migrate_schemas --tenant --noinput && python3 manage.py init_prod && gunicorn config.wsgi --bind 0.0.0.0:$PORT"
