# Generated by Django 5.2.9 on 2026-02-09 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="context_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="conversation",
            name="context_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("section", "Class Section"),
                    ("subject", "Subject Group"),
                    ("department", "Department"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
