# Generated by Django 4.2 on 2026-01-20 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academic", "0001_initial"),
        ("core", "0001_initial"),
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="tenant",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscription",
                to="core.tenant",
            ),
        ),
        migrations.AddField(
            model_name="studentfee",
            name="fee_structure",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assigned_fees",
                to="billing.feestructure",
            ),
        ),
        migrations.AddField(
            model_name="studentfee",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fees",
                to="academic.student",
            ),
        ),
        migrations.AddField(
            model_name="studentfee",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_fees",
                to="core.tenant",
            ),
        ),
    ]
