# Generated by Django 4.2 on 2026-01-17 06:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                (
                    "plan_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "price_monthly",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "price_yearly",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("currency", models.CharField(default="USD", max_length=10)),
                ("student_limit", models.IntegerField(default=100)),
                ("teacher_limit", models.IntegerField(default=10)),
                ("storage_limit_gb", models.IntegerField(default=10)),
                ("ai_token_limit", models.IntegerField(default=50000)),
                ("has_ai_tutor", models.BooleanField(default=False)),
                ("has_ai_eval", models.BooleanField(default=False)),
                ("has_parent_portal", models.BooleanField(default=False)),
                ("has_analytics", models.BooleanField(default=False)),
                ("has_career_guidance", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="active",
        ),
        migrations.AddField(
            model_name="subscription",
            name="auto_renew",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="subscription",
            name="billing_cycle",
            field=models.CharField(
                choices=[("monthly", "Monthly"), ("yearly", "Yearly")],
                default="monthly",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("past_due", "Past Due"),
                    ("cancelled", "Cancelled"),
                    ("trial", "Trial"),
                ],
                default="active",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="billing.subscriptionplan",
            ),
        ),
    ]
