# Generated by Django 5.2.9 on 2026-03-02 15:45

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionPlanHistory",
            fields=[
                (
                    "history_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "previous_plan_name",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "new_plan_name",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("previous_plan_snapshot", models.JSONField(blank=True, default=dict)),
                ("new_plan_snapshot", models.JSONField(blank=True, default=dict)),
                (
                    "previous_status",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("new_status", models.CharField(blank=True, default="", max_length=20)),
                (
                    "previous_billing_cycle",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "new_billing_cycle",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("reason", models.TextField(blank=True, null=True)),
                ("effective_date", models.DateField(default=django.utils.timezone.now)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subscription_plan_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "new_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="history_new_plan",
                        to="billing.subscriptionplan",
                    ),
                ),
                (
                    "previous_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="history_previous_plan",
                        to="billing.subscriptionplan",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plan_history",
                        to="billing.subscription",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription_plan_history",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-changed_at"],
            },
        ),
    ]
