# Generated by Django 5.2.9 on 2026-02-08 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0003_initial"),
        ("core", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="tenant",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expenses",
                to="core.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="feestructure",
            name="tenant",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fee_structures",
                to="core.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="tenant",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="core.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="studentfee",
            name="tenant",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_fees",
                to="core.tenant",
            ),
        ),
    ]
