# Generated by Django 5.2.9 on 2026-03-05 13:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0013_attendance_student_indexes"),
        ("billing", "0004_billingidempotencykey"),
        ("core", "0005_globalsettings_ai_provider_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(
                fields=["tenant", "date"], name="bill_exp_tenant_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(
                fields=["tenant", "category", "date"], name="bill_exp_t_cat_d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["tenant", "payment_date"], name="bill_pay_tenant_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["student", "payment_date"], name="bill_pay_student_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentfee",
            index=models.Index(
                fields=["tenant", "status", "due_date"],
                name="bill_stfee_t_stat_due_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="studentfee",
            index=models.Index(
                fields=["student", "status"], name="bill_stfee_student_stat_idx"
            ),
        ),
    ]
