# Generated by Django 5.2.9 on 2026-03-10 01:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0005_expense_bill_exp_tenant_date_idx_and_more"),
        ("core", "0008_job"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentfee",
            name="discount_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name="FeeDiscount",
            fields=[
                (
                    "discount_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "discount_type",
                    models.CharField(
                        choices=[("percentage", "Percentage"), ("flat", "Flat Amount")],
                        default="percentage",
                        max_length=20,
                    ),
                ),
                ("value", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "max_cap",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum discount cap (for percentage type)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fee_discounts",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="studentfee",
            name="discount",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="applied_fees",
                to="billing.feediscount",
            ),
        ),
    ]
