# Generated by Django 5.2.9 on 2026-05-12 02:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0022_noticeread"),
        ("billing", "0006_studentfee_discount_amount_feediscount_and_more"),
        ("core", "0011_tenant_billing_identity_phase_a"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="bill_number",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Sequential bill number per tenant per FY (Nepali IRD convention).",
                max_length=40,
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("bill_number", ""), _negated=True),
                fields=("tenant", "bill_number"),
                name="bill_pay_tenant_billno_uniq",
            ),
        ),
    ]
