# Generated by Django 5.2.9 on 2026-05-12 15:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0007_payment_bill_number_phase_a"),
        ("billing_school", "0003_nas_je_entry_number_unique_constraint"),
        ("core", "0011_tenant_billing_identity_phase_a"),
    ]

    operations = [
        migrations.AddField(
            model_name="feestructure",
            name="grace_days",
            field=models.PositiveIntegerField(
                default=0, help_text="Days after due_date before the late fee kicks in."
            ),
        ),
        migrations.AddField(
            model_name="feestructure",
            name="late_fee_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Flat NPR amount or percent (0–100) depending on late_fee_type.",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="feestructure",
            name="late_fee_type",
            field=models.CharField(
                choices=[
                    ("none", "No Late Fee"),
                    ("flat", "Flat Amount"),
                    ("percent", "Percent of Balance"),
                ],
                default="none",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="studentfee",
            name="late_fee_applied",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="studentfee",
            name="late_fee_applied_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="FeeHead",
            fields=[
                (
                    "head_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. Admission, Tuition, Library, Transport",
                        max_length=80,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "coa_account",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Income account this head posts to (optional).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fee_heads",
                        to="billing_school.chartofaccount",
                    ),
                ),
                (
                    "fee_structure",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="heads",
                        to="billing.feestructure",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fee_heads",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "name"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "fee_structure"],
                        name="bill_feehead_t_struct_idx",
                    )
                ],
            },
        ),
    ]
