# Generated by Django 5.2.9 on 2026-05-12 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0008_fee_heads_and_late_fee_phase_c"),
    ]

    operations = [
        migrations.AddField(
            model_name="feediscount",
            name="scholarship_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Not a Scholarship"),
                    ("dalit", "Dalit"),
                    ("janajati", "Janajati"),
                    ("madhesi", "Madhesi"),
                    ("muslim", "Muslim"),
                    ("karnali", "Karnali Province"),
                    ("differently_abled", "Differently-abled"),
                    ("female_remote", "Girl Student (Remote Area)"),
                    ("orphan", "Orphan / Single-parent"),
                    ("martyr_family", "Martyr / Conflict-victim Family"),
                    ("free_books", "Free Books Scheme"),
                    ("staff_child", "Staff Child Concession"),
                    ("sibling", "Sibling Discount"),
                    ("merit", "Merit / Top Performer"),
                    ("other", "Other"),
                ],
                default="",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="feediscount",
            name="scholarship_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Not a Scholarship"),
                    ("school_own", "School-funded"),
                    ("govt_ssdp", "Govt SSDP"),
                    ("govt_egrp", "Govt EGRP"),
                    ("govt_local", "Local Govt / Palika"),
                    ("donor_private", "Private Donor"),
                    ("donor_ngo", "NGO / INGO"),
                    ("other", "Other"),
                ],
                default="",
                max_length=24,
            ),
        ),
    ]
