# Generated by Django 5.2.9 on 2026-05-07 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0021_live_session"),
        ("projects", "0002_rubrictemplate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="section",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Primary class section for the project. Optional — members can span multiple sections (cross-class collaboration).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projects",
                to="academic.section",
            ),
        ),
    ]
