# Generated by Django 5.2.9 on 2026-06-11 02:36

import core.upload_validation
import projects.models.attachment
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_alter_project_section"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectattachment",
            name="file",
            field=models.FileField(
                upload_to=projects.models.attachment.project_attachment_upload_to,
                validators=[
                    core.upload_validation.MaxFileSizeValidator(),
                    core.upload_validation.SafeFileContentValidator(
                        frozenset(
                            [
                                "csv",
                                "doc",
                                "docx",
                                "gif",
                                "jpeg",
                                "jpg",
                                "m4a",
                                "md",
                                "mp3",
                                "mp4",
                                "odp",
                                "ods",
                                "odt",
                                "pdf",
                                "png",
                                "ppt",
                                "pptx",
                                "txt",
                                "wav",
                                "webm",
                                "webp",
                                "xls",
                                "xlsx",
                                "zip",
                            ]
                        )
                    ),
                ],
            ),
        ),
    ]
