# Generated by Django 5.2.9 on 2026-04-05 01:52

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0006_studentfee_discount_amount_feediscount_and_more"),
        ("billing_school", "0001_initial"),
        ("core", "0008_job"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChartOfAccount",
            fields=[
                (
                    "account_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "account_code",
                    models.CharField(help_text="e.g. 1010, 4100, 5010", max_length=10),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "name_np",
                    models.CharField(
                        blank=True, help_text="Nepali name", max_length=120
                    ),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("asset", "Asset (सम्पत्ति)"),
                            ("liability", "Liability (दायित्व)"),
                            ("equity", "Accumulated Fund (सञ्चित कोष)"),
                            ("income", "Income (आय)"),
                            ("expenditure", "Expenditure (खर्च)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "sub_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("current_asset", "Current Asset"),
                            ("fixed_asset", "Fixed / Non-current Asset"),
                            ("cash_equivalent", "Cash & Cash Equivalent"),
                            ("receivable", "Receivable"),
                            ("current_liability", "Current Liability"),
                            ("long_term_liability", "Long-term Liability"),
                            ("tds_payable", "TDS Payable"),
                            ("accumulated_fund", "Accumulated Fund"),
                            ("restricted_fund", "Restricted Fund"),
                            ("unrestricted_fund", "Unrestricted Fund"),
                            ("fee_income", "Fee Income"),
                            ("grant_income", "Government / Donor Grant"),
                            ("donation_income", "Donation / Voluntary"),
                            ("other_income", "Other Income"),
                            ("staff_expense", "Staff Salary & Benefits"),
                            ("admin_expense", "Administration Expense"),
                            ("program_expense", "Programme / Academic Expense"),
                            ("depreciation", "Depreciation"),
                            ("bank_charge", "Bank Charge / MSF"),
                            ("tax_expense", "Tax / TDS Expense"),
                            ("other_expense", "Other Expenditure"),
                        ],
                        max_length=25,
                    ),
                ),
                (
                    "is_system",
                    models.BooleanField(
                        default=False, help_text="System accounts cannot be deleted"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="billing_school.chartofaccount",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chart_of_accounts",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["account_code"],
            },
        ),
        migrations.CreateModel(
            name="FundAccount",
            fields=[
                (
                    "fund_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("name_np", models.CharField(blank=True, max_length=120)),
                (
                    "fund_type",
                    models.CharField(
                        choices=[
                            ("unrestricted", "Unrestricted Fund (General)"),
                            ("restricted", "Restricted Fund (Donor/Govt)"),
                            ("endowment", "Endowment Fund"),
                        ],
                        default="unrestricted",
                        max_length=15,
                    ),
                ),
                (
                    "purpose",
                    models.TextField(
                        blank=True,
                        help_text="Purpose/restriction from donor or government",
                    ),
                ),
                ("donor", models.CharField(blank=True, max_length=120)),
                (
                    "opening_balance",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "linked_account",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Chart of Account representing this fund",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fund_account",
                        to="billing_school.chartofaccount",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fund_accounts",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["fund_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="JournalEntry",
            fields=[
                (
                    "entry_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "entry_number",
                    models.CharField(
                        blank=True,
                        help_text="Auto-generated voucher number e.g. JV-2081-00042",
                        max_length=20,
                    ),
                ),
                (
                    "date_ad",
                    models.DateField(help_text="Gregorian date (system timestamp)"),
                ),
                (
                    "date_bs",
                    models.CharField(
                        blank=True,
                        help_text="BS date string YYYY-MM-DD (e.g. 2081-04-15)",
                        max_length=10,
                    ),
                ),
                (
                    "fiscal_year",
                    models.CharField(
                        blank=True,
                        help_text="Nepali fiscal year e.g. 2080/2081",
                        max_length=10,
                    ),
                ),
                ("description", models.CharField(max_length=300)),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("fee_receipt", "Fee Receipt"),
                            ("expense", "Expense Payment"),
                            ("gateway_msf", "Gateway MSF Auto-post"),
                            ("tds_deduction", "TDS Deduction"),
                            ("tds_deposit", "TDS Deposit to IRD"),
                            ("payroll", "Payroll"),
                            ("depreciation", "Depreciation"),
                            ("fund_transfer", "Fund Transfer"),
                            ("opening", "Opening Balance"),
                            ("manual", "Manual Journal"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        help_text="Voucher no, cheque no, txn ID",
                        max_length=100,
                    ),
                ),
                (
                    "is_posted",
                    models.BooleanField(
                        default=False, help_text="Once posted, lines cannot be edited"
                    ),
                ),
                ("narration", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="journal_entries_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journal_entries",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_ad", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InventoryItem",
            fields=[
                (
                    "item_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "item_code",
                    models.CharField(
                        blank=True,
                        help_text="Internal asset tag / barcode",
                        max_length=30,
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("name_np", models.CharField(blank=True, max_length=150)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("furniture", "Furniture & Fixtures"),
                            ("equipment", "Office / Lab Equipment"),
                            ("computer", "Computer & IT Assets"),
                            ("vehicle", "Vehicle"),
                            ("building", "Building / Infrastructure"),
                            ("library_book", "Library Books"),
                            ("sports", "Sports Equipment"),
                            ("consumable", "Consumable / Supplies"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "form_type",
                    models.CharField(
                        choices=[
                            ("401", "Form 401 – Capital Assets Register"),
                            ("403", "Form 403 – Store/Consumables Register"),
                            ("405", "Form 405 – Condemned Assets Register"),
                        ],
                        default="401",
                        max_length=3,
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("unit", models.CharField(default="pcs", max_length=20)),
                ("purchase_date", models.DateField()),
                ("purchase_date_bs", models.CharField(blank=True, max_length=10)),
                (
                    "purchase_price",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                ("supplier", models.CharField(blank=True, max_length=150)),
                (
                    "depreciation_method",
                    models.CharField(
                        choices=[
                            ("straight_line", "Straight Line Method (SLM)"),
                            ("diminishing", "Diminishing Balance Method (DBM)"),
                            ("none", "No Depreciation (Land / Consumable)"),
                        ],
                        default="straight_line",
                        max_length=15,
                    ),
                ),
                (
                    "useful_life_years",
                    models.PositiveSmallIntegerField(
                        default=5, help_text="Estimated useful life in years"
                    ),
                ),
                (
                    "nepali_dep_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("20.00"),
                        help_text="Depreciation rate % per Nepal Govt schedule",
                        max_digits=5,
                    ),
                ),
                (
                    "accumulated_depreciation",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Room / Block / Department",
                        max_length=100,
                    ),
                ),
                (
                    "custodian",
                    models.CharField(
                        blank=True,
                        help_text="Name of responsible staff member",
                        max_length=100,
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("good", "Good"),
                            ("fair", "Fair"),
                            ("poor", "Poor / Needs Repair"),
                            ("condemned", "Condemned / Write-off"),
                        ],
                        default="good",
                        max_length=10,
                    ),
                ),
                ("disposal_date", models.DateField(blank=True, null=True)),
                ("disposal_date_bs", models.CharField(blank=True, max_length=10)),
                ("disposal_reason", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_items",
                        to="core.tenant",
                    ),
                ),
                (
                    "purchase_journal",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inventory_purchases",
                        to="billing_school.journalentry",
                    ),
                ),
            ],
            options={
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="JournalLine",
            fields=[
                (
                    "line_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "debit",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "credit",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                ("narration", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="journal_lines",
                        to="billing_school.chartofaccount",
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="billing_school.journalentry",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MerchantServiceFee",
            fields=[
                (
                    "msf_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "gateway",
                    models.CharField(
                        choices=[
                            ("esewa", "eSewa"),
                            ("khalti", "Khalti"),
                            ("connectips", "ConnectIPS"),
                        ],
                        max_length=15,
                    ),
                ),
                ("gross_amount", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "msf_rate",
                    models.DecimalField(
                        decimal_places=2, help_text="MSF rate %", max_digits=5
                    ),
                ),
                ("msf_amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("net_amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "journal_entry",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="msf_entries",
                        to="billing_school.journalentry",
                    ),
                ),
                (
                    "payment",
                    models.OneToOneField(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="merchant_service_fee",
                        to="billing.payment",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="merchant_service_fees",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TDSEntry",
            fields=[
                (
                    "tds_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("vendor_name", models.CharField(max_length=150)),
                (
                    "pan_number",
                    models.CharField(
                        blank=True,
                        help_text="PAN / VAT registration number",
                        max_length=20,
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("vendor_supply", "Vendor / Supply Contract"),
                            ("vendor_contract", "Service / Works Contract"),
                            ("rent", "Rent"),
                            ("professional_fee", "Professional / Consultancy"),
                            ("commission", "Commission"),
                            ("salary", "Salary (Payroll)"),
                            ("interest", "Interest"),
                            ("dividend", "Dividend"),
                        ],
                        max_length=20,
                    ),
                ),
                ("payment_date", models.DateField()),
                ("date_bs", models.CharField(blank=True, max_length=10)),
                ("fiscal_year", models.CharField(blank=True, max_length=10)),
                ("gross_amount", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "tds_rate",
                    models.DecimalField(
                        decimal_places=2, help_text="TDS rate (%)", max_digits=5
                    ),
                ),
                ("tds_amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("net_amount", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "tds_section",
                    models.CharField(
                        blank=True, help_text="e.g. Section 88(1)", max_length=30
                    ),
                ),
                (
                    "is_deposited",
                    models.BooleanField(
                        default=False, help_text="Has TDS been deposited to IRD?"
                    ),
                ),
                ("deposit_date", models.DateField(blank=True, null=True)),
                (
                    "deposit_ref",
                    models.CharField(
                        blank=True,
                        help_text="IRD bank challan / receipt reference",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "journal_entry",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tds_entries",
                        to="billing_school.journalentry",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tds_entries",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-payment_date"],
            },
        ),
        migrations.AddIndex(
            model_name="chartofaccount",
            index=models.Index(
                fields=["tenant", "account_type"], name="coa_tenant_type_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="chartofaccount",
            unique_together={("tenant", "account_code")},
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(fields=["tenant", "date_ad"], name="je_tenant_date_idx"),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(
                fields=["tenant", "entry_type"], name="je_tenant_type_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inventoryitem",
            index=models.Index(
                fields=["tenant", "category"], name="inv_tenant_cat_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inventoryitem",
            index=models.Index(
                fields=["tenant", "form_type"], name="inv_tenant_form_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="journalline",
            index=models.Index(
                fields=["entry", "account"], name="jl_entry_account_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tdsentry",
            index=models.Index(
                fields=["tenant", "payment_date"], name="tds_tenant_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tdsentry",
            index=models.Index(
                fields=["tenant", "fiscal_year"], name="tds_tenant_fy_idx"
            ),
        ),
    ]
