# Generated by Django 5.2.9 on 2026-04-05 02:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing_school", "0002_nas_accounting"),
        ("core", "0008_job"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="journalentry",
            constraint=models.UniqueConstraint(
                condition=models.Q(("entry_number", ""), _negated=True),
                fields=("tenant", "entry_number"),
                name="je_tenant_entry_number_uniq",
            ),
        ),
    ]
