# Generated by Django 5.2.9 on 2026-03-10 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transport", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="studenttransportassignment",
            new_name="transport_assign_active_idx",
            old_name="transport_assign_tenant_active_idx",
        ),
    ]
