# Generated by Django 5.2.9 on 2026-02-21 06:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AIInteractionLog",
            fields=[
                (
                    "log_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("feature_used", models.CharField(max_length=100)),
                ("prompt_tokens", models.IntegerField(default=0)),
                ("completion_tokens", models.IntegerField(default=0)),
                ("total_tokens", models.IntegerField(default=0)),
                (
                    "cost_estimated",
                    models.DecimalField(decimal_places=6, default=0.0, max_digits=10),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="LearningNode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("order", models.IntegerField(default=0)),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("video", "Video"),
                            ("article", "Article"),
                            ("quiz", "Quiz"),
                            ("assignment", "Assignment"),
                            ("topic", "Topic Concept"),
                        ],
                        default="topic",
                        max_length=50,
                    ),
                ),
                (
                    "resource_link",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("estimated_minutes", models.IntegerField(default=15)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("locked", "Locked"),
                            ("unlocked", "Unlocked"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                        ],
                        default="locked",
                        max_length=20,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="LearningPath",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("generated_by_ai", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="StudentAIReport",
            fields=[
                (
                    "report_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("report_data", models.JSONField()),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("is_automated", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="StudyEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("class", "Class Session"),
                            ("study", "Self Study"),
                            ("assignment", "Assignment due"),
                            ("exam", "Exam Prep"),
                            ("break", "Break"),
                        ],
                        default="study",
                        max_length=50,
                    ),
                ),
                ("is_completed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
