# Generated by Django 4.2 on 2026-01-20 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("ai_engine", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="aiinteractionlog",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.tenant"
            ),
        ),
    ]
