# Generated by Django 5.2.9 on 2026-02-21 06:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academic", "0003_initial"),
        ("ai_engine", "0002_initial"),
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="aiinteractionlog",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="learningnode",
            name="lesson",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="learning_nodes",
                to="academic.lesson",
            ),
        ),
        migrations.AddField(
            model_name="learningpath",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="learning_paths",
                to="academic.student",
            ),
        ),
        migrations.AddField(
            model_name="learningpath",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="learning_paths",
                to="academic.subject",
            ),
        ),
        migrations.AddField(
            model_name="learningpath",
            name="tenant",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.tenant",
            ),
        ),
        migrations.AddField(
            model_name="learningnode",
            name="learning_path",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nodes",
                to="ai_engine.learningpath",
            ),
        ),
        migrations.AddField(
            model_name="studentaireport",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ai_reports",
                to="academic.student",
            ),
        ),
        migrations.AddField(
            model_name="studentaireport",
            name="tenant",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.tenant",
            ),
        ),
        migrations.AddField(
            model_name="studyevent",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="study_events",
                to="academic.student",
            ),
        ),
        migrations.AddField(
            model_name="studyevent",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="academic.subject",
            ),
        ),
        migrations.AddField(
            model_name="studyevent",
            name="tenant",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.tenant",
            ),
        ),
    ]
