# Generated by Django 5.2.9 on 2026-03-05

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import core.vector


def _embedding_dimensions() -> int:
    value = getattr(settings, "AI_EMBEDDING_DIMENSIONS", 1536)
    try:
        return max(1, int(value))
    except (TypeError, ValueError):
        return 1536


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_enable_pgvector_extension"),
        ("ai_engine", "0003_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentChunk",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("lesson", "Lesson"),
                            ("chapter", "Chapter"),
                            ("material", "Material"),
                        ],
                        max_length=20,
                    ),
                ),
                ("source_id", models.CharField(db_index=True, max_length=64)),
                ("text", models.TextField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "embedding",
                    core.vector.VectorField(dimensions=_embedding_dimensions()),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_chunks",
                        to="core.tenant",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="contentchunk",
            index=models.Index(
                fields=["tenant", "source_type"], name="ai_chunk_tenant_type_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contentchunk",
            index=models.Index(
                fields=["tenant", "source_id"], name="ai_chunk_tenant_source_idx"
            ),
        ),
    ]
