# Generated by Django 4.2 on 2026-01-21 13:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0007_attendance"),
        ("core", "0002_initial"),
        ("ai_engine", "0003_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentAIReport",
            fields=[
                (
                    "report_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("report_data", models.JSONField()),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("is_automated", models.BooleanField(default=False)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_reports",
                        to="academic.student",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.tenant"
                    ),
                ),
            ],
        ),
    ]
