# Generated by Django 5.2.9 on 2026-03-05

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai_engine", "0004_contentchunk"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AiGeneratedArtifact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "artifact_type",
                    models.CharField(
                        choices=[("summary", "Summary"), ("exam_notes", "Exam Notes")],
                        max_length=32,
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("lesson", "Lesson"),
                            ("chapter", "Chapter"),
                            ("material", "Material"),
                        ],
                        default="lesson",
                        max_length=20,
                    ),
                ),
                ("source_id", models.CharField(db_index=True, max_length=64)),
                (
                    "lang",
                    models.CharField(
                        choices=[("en", "English"), ("ne", "Nepali")],
                        default="en",
                        max_length=2,
                    ),
                ),
                ("content", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_generated_artifacts",
                        to="core.tenant",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="aigeneratedartifact",
            index=models.Index(
                fields=["tenant", "artifact_type", "source_type"],
                name="ai_artifact_tenant_type_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="aigeneratedartifact",
            index=models.Index(
                fields=["tenant", "source_type", "source_id"],
                name="ai_artifact_source_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="aigeneratedartifact",
            index=models.Index(
                fields=["tenant", "lang", "created_at"],
                name="ai_artifact_lang_created_idx",
            ),
        ),
    ]
