# Generated by Django 4.2 on 2026-01-21 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_initial"),
        ("ai_engine", "0004_studentaireport"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aiinteractionlog",
            name="tenant",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="studentaireport",
            name="tenant",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.tenant",
            ),
        ),
    ]
