# Generated by Django 5.2.9 on 2026-03-05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai_engine", "0005_aigeneratedartifact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aigeneratedartifact",
            name="artifact_type",
            field=models.CharField(
                choices=[
                    ("summary", "Summary"),
                    ("exam_notes", "Exam Notes"),
                    ("exam_paper", "Exam Paper"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="aigeneratedartifact",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("lesson", "Lesson"),
                    ("chapter", "Chapter"),
                    ("material", "Material"),
                    ("subject", "Subject"),
                    ("class", "Class"),
                ],
                default="lesson",
                max_length=20,
            ),
        ),
    ]
