# Generated by Django 4.2 on 2026-01-22 03:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0009_notice_tenant"),
        ("core", "0002_initial"),
        ("ai_engine", "0006_learningpath_learningnode"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudyEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("class", "Class Session"),
                            ("study", "Self Study"),
                            ("assignment", "Assignment due"),
                            ("exam", "Exam Prep"),
                            ("break", "Break"),
                        ],
                        default="study",
                        max_length=50,
                    ),
                ),
                ("is_completed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_events",
                        to="academic.student",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="academic.subject",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.tenant",
                    ),
                ),
            ],
        ),
    ]
