# Generated by Django 5.2.9 on 2026-03-08 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_engine", "0007_gradingrubric_aigradingdraft"),
    ]

    operations = [
        migrations.AddField(
            model_name="learningnode",
            name="ease_factor",
            field=models.FloatField(
                default=2.5, help_text="SM-2 ease factor (min 1.3)"
            ),
        ),
        migrations.AddField(
            model_name="learningnode",
            name="interval_days",
            field=models.IntegerField(default=1, help_text="Days until next review"),
        ),
        migrations.AddField(
            model_name="learningnode",
            name="last_quality",
            field=models.IntegerField(
                blank=True, help_text="Last recall quality rating (0-5)", null=True
            ),
        ),
        migrations.AddField(
            model_name="learningnode",
            name="next_review_at",
            field=models.DateTimeField(
                blank=True, help_text="Scheduled next review datetime", null=True
            ),
        ),
        migrations.AddField(
            model_name="learningnode",
            name="repetitions",
            field=models.IntegerField(
                default=0, help_text="Number of successful reviews"
            ),
        ),
    ]
