# Generated by Django 5.2.10 on 2026-01-26 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "academic",
            "0010_assessment_section_question_difficulty_question_tags_and_more",
        ),
        ("ai_engine", "0007_studyevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="learningnode",
            name="lesson",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="learning_nodes",
                to="academic.lesson",
            ),
        ),
    ]
