# Generated by Django 5.2.9 on 2026-03-08 17:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0014_alter_lessonmaterial_file_alter_notice_attachment"),
        ("ai_engine", "0009_add_tutor_conversation_message"),
        ("core", "0008_job"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SkillTag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assessments",
                    models.ManyToManyField(
                        blank=True, related_name="skill_tags", to="academic.assessment"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lessons",
                    models.ManyToManyField(
                        blank=True, related_name="skill_tags", to="academic.lesson"
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_tags",
                        to="academic.subject",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_tags",
                        to="core.tenant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SkillPracticeEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "correct",
                    models.BooleanField(
                        help_text="True if the student answered/performed correctly"
                    ),
                ),
                (
                    "score_pct",
                    models.FloatField(
                        default=0.0, help_text="Score as percentage (0-100)"
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("assessment", "Assessment"),
                            ("lesson", "Lesson Review"),
                            ("tutor", "AI Tutor"),
                        ],
                        default="assessment",
                        max_length=20,
                    ),
                ),
                ("source_id", models.CharField(blank=True, default="", max_length=64)),
                ("mastery_before", models.FloatField(default=0.0)),
                ("mastery_after", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_events",
                        to="academic.student",
                    ),
                ),
                (
                    "skill_tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="ai_engine.skilltag",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SkillMastery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "p_mastery",
                    models.FloatField(
                        default=0.1,
                        help_text="Current estimated probability of mastery (0-1)",
                    ),
                ),
                (
                    "p_transit",
                    models.FloatField(default=0.1, help_text="P(learn after practice)"),
                ),
                (
                    "p_slip",
                    models.FloatField(default=0.1, help_text="P(wrong | mastered)"),
                ),
                (
                    "p_guess",
                    models.FloatField(
                        default=0.2, help_text="P(correct | not mastered)"
                    ),
                ),
                (
                    "observations",
                    models.IntegerField(
                        default=0, help_text="Number of practice events seen"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_masteries",
                        to="academic.student",
                    ),
                ),
                (
                    "skill_tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="masteries",
                        to="ai_engine.skilltag",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="skilltag",
            index=models.Index(
                fields=["tenant", "subject"], name="ai_skill_tenant_subject_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="skilltag",
            unique_together={("tenant", "name", "subject")},
        ),
        migrations.AddIndex(
            model_name="skillpracticeevent",
            index=models.Index(
                fields=["student", "skill_tag", "created_at"],
                name="ai_spe_student_skill_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="skillmastery",
            index=models.Index(
                fields=["student", "p_mastery"], name="ai_skill_mastery_student_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="skillmastery",
            unique_together={("student", "skill_tag")},
        ),
    ]
