# Generated by Django 5.2.9 on 2026-03-08 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_engine", "0010_add_bkt_skill_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutormessage",
            name="confidence",
            field=models.FloatField(
                blank=True,
                help_text="RAG confidence score (0-1) for assistant messages",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tutormessage",
            name="confidence_label",
            field=models.CharField(
                blank=True, default="", help_text="high | moderate | low", max_length=16
            ),
        ),
        migrations.AddField(
            model_name="tutormessage",
            name="mode",
            field=models.CharField(
                blank=True,
                default="direct",
                help_text="direct | socratic",
                max_length=16,
            ),
        ),
    ]
