# Generated by Django 5.2.9 on 2026-03-08 17:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0014_alter_lessonmaterial_file_alter_notice_attachment"),
        ("ai_engine", "0011_add_confidence_mode_to_tutor_message"),
        ("core", "0008_job"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AITokenBudget",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "daily_limit_tokens",
                    models.IntegerField(
                        default=10000, help_text="Max tokens per day. 0 = unlimited."
                    ),
                ),
                (
                    "used_today",
                    models.IntegerField(default=0, help_text="Tokens consumed today."),
                ),
                (
                    "reset_at",
                    models.DateTimeField(
                        help_text="Next daily reset timestamp (UTC midnight)."
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Disable to suspend enforcement."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null = tenant-wide budget. Set = per-student override.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_token_budgets",
                        to="academic.student",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_token_budgets",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["tenant", "is_active"],
                        name="ai_budget_tenant_active_idx",
                    ),
                    models.Index(
                        fields=["tenant", "student"],
                        name="ai_budget_tenant_student_idx",
                    ),
                ],
                "unique_together": {("tenant", "student")},
            },
        ),
    ]
