# Generated by Django 5.2.9 on 2026-03-09 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_engine", "0012_add_ai_token_budget"),
    ]

    operations = [
        migrations.AddField(
            model_name="studyevent",
            name="estimated_minutes",
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name="studyevent",
            name="node_id",
            field=models.UUIDField(
                blank=True, help_text="Learning node linked to this session", null=True
            ),
        ),
        migrations.AddField(
            model_name="studyevent",
            name="skill_tag_id",
            field=models.UUIDField(
                blank=True, help_text="Skill gap linked to this session", null=True
            ),
        ),
        migrations.AlterField(
            model_name="studyevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("class", "Class Session"),
                    ("study", "Self Study"),
                    ("assignment", "Assignment due"),
                    ("exam", "Exam Prep"),
                    ("break", "Break"),
                    ("review", "Spaced Review"),
                    ("skill_practice", "Skill Practice"),
                ],
                default="study",
                max_length=50,
            ),
        ),
    ]
