# Generated by Django 5.2.9 on 2026-03-09 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_engine", "0013_add_study_event_planner_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentaireport",
            name="report_type",
            field=models.CharField(
                choices=[
                    ("student", "Student Report"),
                    ("parent", "Parent Report"),
                    ("teacher", "Teacher Report"),
                    ("class", "Class Summary"),
                ],
                default="student",
                max_length=20,
            ),
        ),
    ]
