# Generated by Django 5.2.9 on 2026-03-15 09:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_engine", "0014_add_report_type_to_studentaireport"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutorconversation",
            name="preferred_mode",
            field=models.CharField(
                choices=[("direct", "Direct"), ("socratic", "Socratic")],
                default="direct",
                help_text="Persisted teaching mode (direct | socratic). Auto-selected if not set.",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="aigeneratedartifact",
            name="artifact_type",
            field=models.CharField(
                choices=[
                    ("summary", "Summary"),
                    ("exam_notes", "Exam Notes"),
                    ("exam_paper", "Exam Paper"),
                    ("misconception_report", "Misconception Report"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="aigeneratedartifact",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("lesson", "Lesson"),
                    ("chapter", "Chapter"),
                    ("material", "Material"),
                    ("subject", "Subject"),
                    ("class", "Class"),
                    ("student", "Student"),
                ],
                default="lesson",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="SkillPrerequisite",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "prerequisite",
                    models.ForeignKey(
                        help_text="The skill that must be understood first.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dependents",
                        to="ai_engine.skilltag",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        help_text="The skill that depends on a prerequisite.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prerequisites",
                        to="ai_engine.skilltag",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["skill"], name="ai_prereq_skill_idx"),
                    models.Index(fields=["prerequisite"], name="ai_prereq_prereq_idx"),
                ],
                "unique_together": {("skill", "prerequisite")},
            },
        ),
    ]
