# Copyright (c) 2024-2026 Pramod Singh Manyal. All rights reserved.
# Unauthorized copying, modification, or distribution of this file,
# via any medium, is strictly prohibited. Proprietary and confidential.
"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.1.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import logging
import os
from datetime import timedelta
from pathlib import Path
from urllib.parse import urlsplit

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# Load environment variables from .env file
load_dotenv(BASE_DIR.parent / ".env")
logger = logging.getLogger(__name__)


def _csv_env_list(key: str, default: list[str] | None = None) -> list[str]:
    value = os.environ.get(key, "")
    if not value:
        return list(default or [])
    return [item.strip() for item in value.split(",") if item.strip()]


def _normalize_origin(origin: str) -> str:
    value = (origin or "").strip()
    if not value:
        return ""
    if "://" not in value:
        return value.rstrip("/")
    parsed = urlsplit(value)
    if not parsed.scheme or not parsed.netloc:
        return value.rstrip("/")
    return f"{parsed.scheme}://{parsed.netloc}"


def _normalize_origins(origins: list[str]) -> list[str]:
    normalized: list[str] = []
    seen: set[str] = set()
    for origin in origins:
        candidate = _normalize_origin(origin)
        if not candidate or candidate in seen:
            continue
        normalized.append(candidate)
        seen.add(candidate)
    return normalized


def _csrf_safe_origins(origins: list[str]) -> list[str]:
    """Filter CSRF_TRUSTED_ORIGINS to entries Django can match.

    Django requires ``scheme://host`` form; subdomain wildcards like
    ``https://*.example.com`` are supported, but bare ``*`` or entries with no
    scheme are rejected silently at runtime. Drop them at startup instead so
    the list is useful.
    """
    safe: list[str] = []
    for origin in origins:
        value = (origin or "").strip()
        if not value or value == "*" or "://" not in value:
            continue
        scheme, _, rest = value.partition("://")
        if not scheme or not rest or rest.startswith("*") and not rest.startswith("*."):
            continue
        safe.append(value)
    return safe


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "False").lower() == "true"

# SECURITY WARNING: keep the secret key used in production secret!
# Never ship with a hardcoded fallback — reject missing keys in non-debug envs.
SECRET_KEY = (os.environ.get("SECRET_KEY", "") or "").strip()
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = "django-insecure-dev-only-do-not-use-in-production"
        logger.warning(
            "SECRET_KEY is not set; using insecure dev default (DEBUG=True)."
        )
    else:
        raise ImproperlyConfigured(
            "SECRET_KEY environment variable must be set when DEBUG=False."
        )

if DEBUG:
    ALLOWED_HOSTS = _csv_env_list("ALLOWED_HOSTS", ["localhost", "127.0.0.1"])
else:
    ALLOWED_HOSTS = _csv_env_list("ALLOWED_HOSTS", [])
    if not ALLOWED_HOSTS:
        raise RuntimeError(
            "ALLOWED_HOSTS must be explicitly configured when DEBUG=False."
        )


def _append_allowed_host(host: str) -> None:
    candidate = (host or "").strip()
    if not candidate or "*" in ALLOWED_HOSTS or candidate in ALLOWED_HOSTS:
        return
    ALLOWED_HOSTS.append(candidate)


# Railway health checks use this Host header.
_append_allowed_host("healthcheck.railway.app")
_append_allowed_host(os.environ.get("RAILWAY_PUBLIC_DOMAIN", ""))
_append_allowed_host(os.environ.get("RAILWAY_PRIVATE_DOMAIN", ""))

# Primary SaaS domain used for wildcard tenant hostnames (e.g. demo.example.com).
BASE_DOMAIN = (os.environ.get("BASE_DOMAIN", "") or "").strip().lower()
if BASE_DOMAIN:
    _append_allowed_host(BASE_DOMAIN)
    _append_allowed_host(f".{BASE_DOMAIN}")


# Application definition

# Multi-Tenancy Configuration
SHARED_APPS = [
    "daphne",  # ASGI server — must be first for runserver to use ASGI
    "channels",  # WebSocket layer
    "django_tenants",  # mandatory
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "corsheaders",
    "core",
    "billing",
    "billing_saas",
    "users",  # Hybrid App (Exists in both)
    "auditlog",
]

TENANT_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "corsheaders",
    "users",
    "academic.apps.AcademicConfig",
    "billing",
    "billing_school",
    "ai_engine",
    "reports",
    "notifications",
    "library",
    "gamification",
    "conversations",
    "hr_payroll",
    "transport",
    "hostel",
    "projects",
]

INSTALLED_APPS = list(SHARED_APPS) + [
    app for app in TENANT_APPS if app not in SHARED_APPS
]

# Hybrid *project* apps are allowed only when explicitly approved.
# Framework-level overlaps (django/rest/auth/cors) are expected in django-tenants.
ALLOWED_HYBRID_APPS = set(_csv_env_list("ALLOWED_HYBRID_APPS", ["users", "billing"]))
OVERLAPPING_APPS = set(SHARED_APPS).intersection(TENANT_APPS)
FRAMEWORK_OVERLAP_PREFIXES = ("django.",)
FRAMEWORK_OVERLAP_APPS = {
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "corsheaders",
}
PROJECT_OVERLAPPING_APPS = {
    app
    for app in OVERLAPPING_APPS
    if not app.startswith(FRAMEWORK_OVERLAP_PREFIXES)
    and app not in FRAMEWORK_OVERLAP_APPS
}
UNEXPECTED_HYBRID_APPS = sorted(
    PROJECT_OVERLAPPING_APPS.difference(ALLOWED_HYBRID_APPS)
)
if UNEXPECTED_HYBRID_APPS:
    raise ImproperlyConfigured(
        "Unexpected SHARED_APPS/TENANT_APPS overlap detected: "
        f"{', '.join(UNEXPECTED_HYBRID_APPS)}. "
        "Move app to a single schema scope or add explicit override via ALLOWED_HYBRID_APPS."
    )

TENANT_MODEL = "core.Tenant"
TENANT_DOMAIN_MODEL = "core.Domain"


AUTH_USER_MODEL = "users.UserAccount"

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",  # Must be as high as possible
    "django.middleware.security.SecurityMiddleware",
    "core.middleware.SecurityHeadersMiddleware",
    "core.middleware.RequestContextMiddleware",
    "core.metrics.PrometheusMetricsMiddleware",
    "core.middleware.TenantFromHeaderMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "auditlog.middleware.AuditlogMiddleware",
]

DATABASE_ROUTERS = ("django_tenants.routers.TenantSyncRouter",)

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

import dj_database_url

DATABASE_URL = os.environ.get("DATABASE_URL")
if not DATABASE_URL:
    DATABASE_URL = f"postgres://{os.environ.get('DB_USER', 'postgres')}:{os.environ.get('DB_PASSWORD', '')}@{os.environ.get('DB_HOST', '127.0.0.1')}:{os.environ.get('DB_PORT', '5432')}/elearning"

DATABASES = {
    "default": dj_database_url.parse(
        DATABASE_URL,
        engine="django_tenants.postgresql_backend",
        conn_max_age=600,
    )
}

if not DATABASES["default"].get("NAME"):
    DATABASES["default"]["NAME"] = "elearning"
if DATABASES["default"].get("NAME") == "":
    DATABASES["default"]["NAME"] = "elearning"

if DEBUG:
    logger.debug(
        "Database configured",
        extra={
            "db_engine": DATABASES["default"].get("ENGINE"),
            "db_host": DATABASES["default"].get("HOST"),
            "db_name": DATABASES["default"].get("NAME"),
        },
    )


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = os.environ.get("TIME_ZONE", "Asia/Kathmandu")

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Upload hardening — enforced by core.upload_validation validators on every
# user-supplied FileField/ImageField and direct request.FILES handler.
UPLOAD_MAX_SIZE_MB = int(os.environ.get("UPLOAD_MAX_SIZE_MB", "25"))
# Cap multipart parts Django will parse per request (defense in depth).
DATA_UPLOAD_MAX_NUMBER_FILES = int(os.environ.get("DATA_UPLOAD_MAX_NUMBER_FILES", "20"))

# Bearer token guarding /api/metrics (Prometheus scrape). When unset in a
# non-debug deployment the endpoint fails closed (404). Configure the scraper
# with `authorization: Bearer <token>`.
METRICS_TOKEN = (os.environ.get("METRICS_TOKEN", "") or "").strip()

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# CORS Configuration
_frontend_url_env = (os.environ.get("FRONTEND_URL", "") or "").strip().rstrip("/")
FRONTEND_URL = _frontend_url_env or "http://localhost:3000"

if DEBUG:
    CORS_ALLOWED_ORIGINS = _csv_env_list(
        "CORS_ALLOWED_ORIGINS",
        ["http://localhost:3000", "http://127.0.0.1:3000"],
    )
else:
    # In production, CORS must be explicit.
    CORS_ALLOWED_ORIGINS = _csv_env_list("CORS_ALLOWED_ORIGINS", [])

frontend_origin = _normalize_origin(_frontend_url_env)
if frontend_origin and frontend_origin not in CORS_ALLOWED_ORIGINS:
    CORS_ALLOWED_ORIGINS.append(frontend_origin)

CORS_ALLOWED_ORIGINS = _normalize_origins(CORS_ALLOWED_ORIGINS)

_cors_origin_regexes = _csv_env_list("CORS_ALLOWED_ORIGIN_REGEXES", [])
if _cors_origin_regexes:
    CORS_ALLOWED_ORIGIN_REGEXES = _cors_origin_regexes
elif DEBUG:
    CORS_ALLOWED_ORIGIN_REGEXES = [r"^https:\/\/.*\.vercel\.app$"]
else:
    CORS_ALLOWED_ORIGIN_REGEXES = []

CORS_ALLOW_ALL_ORIGINS = (
    os.environ.get("CORS_ALLOW_ALL_ORIGINS", "false").lower() == "true"
)
if CORS_ALLOW_ALL_ORIGINS and not DEBUG:
    # Credentials are allowed below; combined with wildcard origins any site
    # could make authenticated requests on behalf of logged-in users.
    raise ImproperlyConfigured(
        "CORS_ALLOW_ALL_ORIGINS must not be enabled when DEBUG=False. "
        "List explicit origins in CORS_ALLOWED_ORIGINS instead."
    )
CORS_ALLOW_CREDENTIALS = True

_csrf_trusted_from_env = _csv_env_list("CSRF_TRUSTED_ORIGINS", [])
CSRF_TRUSTED_ORIGINS = _csrf_safe_origins(
    _normalize_origins(_csrf_trusted_from_env or list(CORS_ALLOWED_ORIGINS))
)

from corsheaders.defaults import default_headers

CORS_ALLOW_HEADERS = list(default_headers) + [
    "x-tenant-id",
]

# REST Framework Configuration - Allow public access for demo
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "users.authentication.TenantAwareJWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        # Keep anonymous traffic constrained, but avoid long lockouts for authenticated SPA usage.
        "anon": os.environ.get("THROTTLE_ANON", "300/hour"),
        "user": os.environ.get("THROTTLE_USER", "5000/hour"),
        "auth_login": os.environ.get("THROTTLE_AUTH_LOGIN", "20/min"),
        "auth_refresh": os.environ.get("THROTTLE_AUTH_REFRESH", "40/min"),
        "auth_register": os.environ.get("THROTTLE_AUTH_REGISTER", "5/hour"),
        "auth_password_reset": os.environ.get("THROTTLE_AUTH_PASSWORD_RESET", "5/hour"),
        "auth_password_reset_confirm": os.environ.get(
            "THROTTLE_AUTH_PASSWORD_RESET_CONFIRM", "10/hour"
        ),
        "ai_tutor_chat": os.environ.get("THROTTLE_AI_TUTOR_CHAT", "30/min"),
    },
    "DEFAULT_PAGINATION_CLASS": "core.pagination.StandardResultsSetPagination",
    "PAGE_SIZE": 20,
    "EXCEPTION_HANDLER": "core.exceptions.api_exception_handler",
    "DEFAULT_SCHEMA_CLASS": "core.schema.UniqueOperationIdAutoSchema",
}

MAX_PAGE_SIZE = int(os.environ.get("MAX_PAGE_SIZE", "100"))

_jwt_default_access_minutes = int(os.environ.get("JWT_ACCESS_MINUTES_DEFAULT", "60"))
_jwt_default_refresh_days = int(os.environ.get("JWT_REFRESH_DAYS_DEFAULT", "7"))

SIMPLE_JWT = {
    "USER_ID_FIELD": "user_id",
    "USER_ID_CLAIM": "user_id",
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=_jwt_default_access_minutes),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=_jwt_default_refresh_days),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "AUTH_HEADER_TYPES": ("Bearer",),
}

JWT_ROLE_TOKEN_LIFETIMES = {
    # High-risk roles get shorter lifetimes.
    "saas_admin": {
        "access": timedelta(
            minutes=int(os.environ.get("JWT_ACCESS_MINUTES_SAAS_ADMIN", "15"))
        ),
        # Session-scoped: 8-hour workday maximum; configure via JWT_REFRESH_HOURS_SAAS_ADMIN
        "refresh": timedelta(
            hours=int(os.environ.get("JWT_REFRESH_HOURS_SAAS_ADMIN", "8"))
        ),
    },
    "saas_staff": {
        "access": timedelta(
            minutes=int(os.environ.get("JWT_ACCESS_MINUTES_SAAS_STAFF", "30"))
        ),
        "refresh": timedelta(
            hours=int(os.environ.get("JWT_REFRESH_HOURS_SAAS_STAFF", "8"))
        ),
    },
    "admin": {
        "access": timedelta(
            minutes=int(os.environ.get("JWT_ACCESS_MINUTES_ADMIN", "20"))
        ),
        "refresh": timedelta(days=int(os.environ.get("JWT_REFRESH_DAYS_ADMIN", "2"))),
    },
    "staff": {
        "access": timedelta(
            minutes=int(os.environ.get("JWT_ACCESS_MINUTES_STAFF", "30"))
        ),
        "refresh": timedelta(days=int(os.environ.get("JWT_REFRESH_DAYS_STAFF", "3"))),
    },
    "teacher": {
        "access": timedelta(
            minutes=int(os.environ.get("JWT_ACCESS_MINUTES_TEACHER", "45"))
        ),
        "refresh": timedelta(days=int(os.environ.get("JWT_REFRESH_DAYS_TEACHER", "5"))),
    },
    "parent": {
        "access": timedelta(
            minutes=int(os.environ.get("JWT_ACCESS_MINUTES_PARENT", "60"))
        ),
        "refresh": timedelta(days=int(os.environ.get("JWT_REFRESH_DAYS_PARENT", "7"))),
    },
    "student": {
        "access": timedelta(
            minutes=int(os.environ.get("JWT_ACCESS_MINUTES_STUDENT", "60"))
        ),
        "refresh": timedelta(days=int(os.environ.get("JWT_REFRESH_DAYS_STUDENT", "7"))),
    },
}

JWT_STRICT_REFRESH_ROTATION = (
    os.environ.get("JWT_STRICT_REFRESH_ROTATION", "true").lower() == "true"
)

# SaaS Admin IP Allowlist — comma-separated CIDRs/IPs.
# Empty = allow all (dev default). Set in production to restrict SaaS admin login
# to known office/VPN IPs. Example: "203.0.113.10,10.0.0.0/8"
SAAS_ADMIN_ALLOWED_IPS: list[str] = [
    ip.strip()
    for ip in os.environ.get("SAAS_ADMIN_ALLOWED_IPS", "").split(",")
    if ip.strip()
]

# TOTP issuer name shown in authenticator apps
TOTP_ISSUER_NAME = os.environ.get("TOTP_ISSUER_NAME", "E-Learning Platform")

# Email configuration
# Uses console backend in DEBUG by default, SMTP in production.
EMAIL_BACKEND = os.environ.get(
    "EMAIL_BACKEND",
    (
        "django.core.mail.backends.console.EmailBackend"
        if DEBUG
        else "django.core.mail.backends.smtp.EmailBackend"
    ),
)
EMAIL_HOST = os.environ.get("EMAIL_HOST", "localhost")
EMAIL_PORT = int(os.environ.get("EMAIL_PORT", "25"))
EMAIL_USE_TLS = os.environ.get("EMAIL_USE_TLS", "false").lower() == "true"
EMAIL_USE_SSL = os.environ.get("EMAIL_USE_SSL", "false").lower() == "true"
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")
EMAIL_TIMEOUT = int(os.environ.get("EMAIL_TIMEOUT", "10"))
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", "support@elearning.dev")
SERVER_EMAIL = os.environ.get("SERVER_EMAIL", DEFAULT_FROM_EMAIL)
RESEND_API_KEY = (os.environ.get("RESEND_API_KEY", "") or "").strip()
RESEND_API_URL = (
    os.environ.get("RESEND_API_URL", "https://api.resend.com/emails") or ""
).strip()
RESEND_REQUEST_TIMEOUT = int(os.environ.get("RESEND_REQUEST_TIMEOUT", "10"))

if EMAIL_USE_TLS and EMAIL_USE_SSL:
    raise ImproperlyConfigured("EMAIL_USE_TLS and EMAIL_USE_SSL cannot both be true.")

if (
    EMAIL_BACKEND == "core.email_backends.resend_backend.ResendAPIEmailBackend"
    and not RESEND_API_KEY
):
    if DEBUG:
        logger.warning(
            "EMAIL_BACKEND is set to Resend API backend but RESEND_API_KEY is empty."
        )
    else:
        raise ImproperlyConfigured(
            "RESEND_API_KEY must be configured when using ResendAPIEmailBackend."
        )

# AI Embeddings / RAG
# Phase 12: Upgraded to text-embedding-3-large (3072 dims) for higher-quality retrieval.
# Existing ContentChunk rows embedded with the old model must be re-indexed:
#   python manage.py ai_index_content --tenant <schema>
# Set AI_EMBEDDING_MODEL=text-embedding-3-small in .env to keep the old model temporarily.
AI_EMBEDDING_DIMENSIONS = int(os.environ.get("AI_EMBEDDING_DIMENSIONS", "3072"))
AI_EMBEDDING_MODEL = os.environ.get(
    "AI_EMBEDDING_MODEL", "text-embedding-3-large"
).strip()
AI_CONTENT_CHUNK_WORDS = int(os.environ.get("AI_CONTENT_CHUNK_WORDS", "180"))
AI_CONTENT_CHUNK_OVERLAP_WORDS = int(
    os.environ.get("AI_CONTENT_CHUNK_OVERLAP_WORDS", "30")
)
AI_TUTOR_TOP_K = int(os.environ.get("AI_TUTOR_TOP_K", "5"))
AI_TUTOR_MIN_SIMILARITY = float(os.environ.get("AI_TUTOR_MIN_SIMILARITY", "0.58"))
AI_WHISPER_MODEL = os.environ.get("AI_WHISPER_MODEL", "whisper-1")
AI_FALLBACK_MODEL = os.environ.get("AI_FALLBACK_MODEL", "gpt-4o-mini")

# AI Risk Analytics
AI_RISK_LOOKBACK_DAYS = int(os.environ.get("AI_RISK_LOOKBACK_DAYS", "30"))
AI_RISK_INACTIVITY_DAYS = int(os.environ.get("AI_RISK_INACTIVITY_DAYS", "14"))
AI_AT_RISK_NOTIFICATION_THRESHOLD = int(
    os.environ.get("AI_AT_RISK_NOTIFICATION_THRESHOLD", "75")
)
AI_AT_RISK_MIN_SCORE = int(os.environ.get("AI_AT_RISK_MIN_SCORE", "40"))
AI_RISK_USE_LLM_EXPLANATIONS = (
    os.environ.get("AI_RISK_USE_LLM_EXPLANATIONS", "false").lower() == "true"
)

# AI Admin Assistant
AI_ADMIN_ASSISTANT_LOOKBACK_DAYS = int(
    os.environ.get("AI_ADMIN_ASSISTANT_LOOKBACK_DAYS", "30")
)
AI_ADMIN_ASSISTANT_USE_LLM_CLASSIFIER = (
    os.environ.get("AI_ADMIN_ASSISTANT_USE_LLM_CLASSIFIER", "false").lower() == "true"
)
AI_ADMIN_ASSISTANT_USE_LLM_RESPONSE = (
    os.environ.get("AI_ADMIN_ASSISTANT_USE_LLM_RESPONSE", "false").lower() == "true"
)

# SMS (Sparrow SMS - Nepal)
SPARROW_SMS_TOKEN = os.environ.get("SPARROW_SMS_TOKEN", "").strip()
SPARROW_SMS_FROM = os.environ.get("SPARROW_SMS_FROM", "School").strip()

# Payment Gateways (Nepal)
ESEWA_MERCHANT_CODE = os.environ.get("ESEWA_MERCHANT_CODE", "EPAYTEST").strip()
ESEWA_PAYMENT_URL = os.environ.get(
    "ESEWA_PAYMENT_URL", "https://uat.esewa.com.np/epay/main"
).strip()
ESEWA_VERIFY_URL = os.environ.get(
    "ESEWA_VERIFY_URL", "https://uat.esewa.com.np/epay/transrec"
).strip()
KHALTI_SECRET_KEY = os.environ.get("KHALTI_SECRET_KEY", "").strip()
KHALTI_INITIATE_URL = os.environ.get(
    "KHALTI_INITIATE_URL", "https://a.khalti.com/api/v2/epayment/initiate/"
).strip()
KHALTI_LOOKUP_URL = os.environ.get(
    "KHALTI_LOOKUP_URL", "https://a.khalti.com/api/v2/epayment/lookup/"
).strip()

# Tenant trust policy:
# - dev_only (default): allow x-tenant-id only in DEBUG + localhost/127.0.0.1/*.local hosts
# - never: ignore x-tenant-id in all envs
TENANT_HEADER_TRUST_MODE = os.environ.get(
    "TENANT_HEADER_TRUST_MODE", "dev_only"
).lower()
# Legacy `/api/billing/*` sunset date (RFC-1123 header generated by billing.legacy mixin).
BILLING_LEGACY_SUNSET = os.environ.get("BILLING_LEGACY_SUNSET", "2026-12-31")

# Security headers baseline
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = "DENY"
SECURE_REFERRER_POLICY = "same-origin"
SECURE_CROSS_ORIGIN_OPENER_POLICY = "same-origin"

_csp_connect_src = ["'self'"]
for _origin in CORS_ALLOWED_ORIGINS:
    if _origin and _origin not in _csp_connect_src:
        _csp_connect_src.append(_origin)
for _origin in _csv_env_list("CSP_CONNECT_SRC_EXTRA", []):
    if _origin and _origin not in _csp_connect_src:
        _csp_connect_src.append(_origin)

SECURITY_CSP_REPORT_ONLY = os.environ.get("CSP_REPORT_ONLY", "false").lower() == "true"
SECURITY_CSP_POLICY = {
    "default-src": ("'self'",),
    "base-uri": ("'self'",),
    "frame-ancestors": ("'none'",),
    "form-action": ("'self'",),
    "object-src": ("'none'",),
    # Keep Django admin and app shells functional while still setting a baseline.
    "script-src": ("'self'", "'unsafe-inline'"),
    "style-src": ("'self'", "'unsafe-inline'"),
    "img-src": ("'self'", "data:", "blob:", "https:"),
    "font-src": ("'self'", "data:"),
    "connect-src": tuple(_csp_connect_src),
}
SECURITY_PERMISSIONS_POLICY = os.environ.get(
    "SECURITY_PERMISSIONS_POLICY",
    "camera=(), microphone=(), geolocation=()",
)

if DEBUG:
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    SECURE_SSL_REDIRECT = False
    SECURE_HSTS_SECONDS = 0
else:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_SSL_REDIRECT = (
        os.environ.get("SECURE_SSL_REDIRECT", "false").lower() == "true"
    )
    SECURE_HSTS_SECONDS = int(
        os.environ.get("SECURE_HSTS_SECONDS", str(60 * 60 * 24 * 30))
    )
    SECURE_HSTS_INCLUDE_SUBDOMAINS = (
        os.environ.get("SECURE_HSTS_INCLUDE_SUBDOMAINS", "true").lower() == "true"
    )
    SECURE_HSTS_PRELOAD = (
        os.environ.get("SECURE_HSTS_PRELOAD", "false").lower() == "true"
    )

# Keep liveness/readiness endpoints reachable over HTTP for platform health probes
# even when SECURE_SSL_REDIRECT is enabled.
_default_secure_redirect_exempt = [
    "healthz/?$",
    "readyz/?$",
    "metrics/?$",
    "api/core/healthz/?$",
    "api/core/readyz/?$",
    "api/core/metrics/?$",
]
SECURE_REDIRECT_EXEMPT = []
for _pattern in _csv_env_list(
    "SECURE_REDIRECT_EXEMPT", _default_secure_redirect_exempt
):
    _normalized_pattern = _pattern.strip().lstrip("/")
    if _normalized_pattern and _normalized_pattern not in SECURE_REDIRECT_EXEMPT:
        SECURE_REDIRECT_EXEMPT.append(_normalized_pattern)

if os.environ.get("SECURE_PROXY_SSL_HEADER"):
    # expected format: HTTP_X_FORWARDED_PROTO,https
    _proxy_parts = [
        p.strip() for p in os.environ["SECURE_PROXY_SSL_HEADER"].split(",", 1)
    ]
    if len(_proxy_parts) == 2 and _proxy_parts[0] and _proxy_parts[1]:
        SECURE_PROXY_SSL_HEADER = (_proxy_parts[0], _proxy_parts[1])

# Enable only when running behind a trusted proxy that forwards tenant hostnames.
USE_X_FORWARDED_HOST = os.environ.get("USE_X_FORWARDED_HOST", "false").lower() == "true"

# Caching Configuration
if "REDIS_URL" in os.environ:
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": os.environ["REDIS_URL"],
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
            },
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "unique-snowflake",
        }
    }

# Async task processing
ASYNC_TASK_BACKEND = os.environ.get("ASYNC_TASK_BACKEND", "sync").strip().lower()
REDIS_URL = os.environ.get("REDIS_URL", "redis://127.0.0.1:6379/1")

# Django Channels — WebSocket layer backed by Redis
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [os.environ.get("REDIS_URL", "redis://127.0.0.1:6379/0")],
            "capacity": 1500,
            "expiry": 60,
        },
    },
}

ASGI_APPLICATION = "config.asgi.application"

CELERY_BROKER_URL = os.environ.get("CELERY_BROKER_URL", REDIS_URL)
CELERY_RESULT_BACKEND = os.environ.get("CELERY_RESULT_BACKEND", REDIS_URL)
CELERY_TASK_ALWAYS_EAGER = (
    os.environ.get("CELERY_TASK_ALWAYS_EAGER", "false").lower() == "true"
)
CELERY_TASK_EAGER_PROPAGATES = (
    os.environ.get("CELERY_TASK_EAGER_PROPAGATES", "true").lower() == "true"
)
CELERY_TASK_STORE_EAGER_RESULT = (
    os.environ.get("CELERY_TASK_STORE_EAGER_RESULT", "true").lower() == "true"
)
CELERY_TASK_DEFAULT_QUEUE = os.environ.get("CELERY_TASK_DEFAULT_QUEUE", "default")
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
ASYNC_JOB_STATUS_TTL_SECONDS = int(
    os.environ.get("ASYNC_JOB_STATUS_TTL_SECONDS", str(60 * 60 * 24))
)

# Audit Log Configuration
AUDITLOG_LOGENTRY_MODEL = "auditlog.LogEntry"
AUDITLOG_DISABLE_REMOTE_ADDR = False
AUDITLOG_CID_GETTER = None
AUDITLOG_CID_HEADER = None

# Structured logging with request and tenant correlation
LOG_LEVEL = os.environ.get("LOG_LEVEL", "INFO").upper()
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "filters": {
        "request_context": {
            "()": "core.logging_context.RequestContextLogFilter",
        },
    },
    "formatters": {
        "json": {
            "()": "core.logging_context.JsonFormatter",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "json",
            "filters": ["request_context"],
        },
    },
    "root": {
        "handlers": ["console"],
        "level": LOG_LEVEL,
    },
}

# Sentry integration (optional; enabled only when package + DSN are available)
SENTRY_DSN = (os.environ.get("SENTRY_DSN", "") or "").strip()
if SENTRY_DSN:
    try:
        import sentry_sdk
        from sentry_sdk.integrations.django import DjangoIntegration

        sentry_sdk.init(
            dsn=SENTRY_DSN,
            environment=os.environ.get("SENTRY_ENVIRONMENT", "production"),
            traces_sample_rate=float(
                os.environ.get("SENTRY_TRACES_SAMPLE_RATE", "0.05")
            ),
            send_default_pii=False,
            integrations=[DjangoIntegration()],
        )
    except Exception as sentry_error:
        logger.warning("Sentry initialization skipped: %s", sentry_error)
