"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.1.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# Load environment variables from .env file
load_dotenv(BASE_DIR.parent / '.env')


def _csv_env_list(key: str, default: list[str] | None = None) -> list[str]:
    value = os.environ.get(key, "")
    if not value:
        return list(default or [])
    return [item.strip() for item in value.split(",") if item.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY", "django-insecure-3lap^-36=51#lal1a^aaimkz_@a9tb=j##w!zj@n@r%7b)ypgf")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "False").lower() == "true"

ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS", "*").split(",")


# Application definition

# Multi-Tenancy Configuration
SHARED_APPS = [
    "django_tenants",  # mandatory
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "corsheaders",
    "core",
    "billing",
    "users", # Hybrid App (Exists in both)
    "gamification",
    "auditlog",
]

TENANT_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "corsheaders",
    "users",
    "academic.apps.AcademicConfig",
    "billing",
    "ai_engine",
    "reports",
    "notifications",
    "library",
    "gamification",
    "conversations",
]

INSTALLED_APPS = list(SHARED_APPS) + [app for app in TENANT_APPS if app not in SHARED_APPS]

TENANT_MODEL = "core.Tenant"
TENANT_DOMAIN_MODEL = "core.Domain"


AUTH_USER_MODEL = 'users.UserAccount'

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",  # Must be as high as possible
    "django.middleware.security.SecurityMiddleware",
    "core.middleware.SecurityHeadersMiddleware",
    "core.middleware.RequestContextMiddleware",
    "core.middleware.TenantFromHeaderMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "auditlog.middleware.AuditlogMiddleware",
]

DATABASE_ROUTERS = (
    'django_tenants.routers.TenantSyncRouter',
)

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

import dj_database_url

DATABASE_URL = os.environ.get("DATABASE_URL")
if not DATABASE_URL:
    DATABASE_URL = f"postgres://{os.environ.get('DB_USER', 'postgres')}:{os.environ.get('DB_PASSWORD', '')}@{os.environ.get('DB_HOST', '127.0.0.1')}:{os.environ.get('DB_PORT', '5432')}/elearning"

DATABASES = {
    "default": dj_database_url.parse(
        DATABASE_URL,
        engine='django_tenants.postgresql_backend',
        conn_max_age=600,
    )
}

if not DATABASES["default"].get("NAME"):
    DATABASES["default"]["NAME"] = "elearning"
if DATABASES["default"].get("NAME") == "":
    DATABASES["default"]["NAME"] = "elearning"

import sys
print(f"DATABASE_URL is: {DATABASE_URL}", file=sys.stderr)
print(f"DATABASES config is: {DATABASES}", file=sys.stderr)


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# CORS Configuration
_frontend_url_env = (os.environ.get("FRONTEND_URL", "") or "").strip().rstrip("/")
FRONTEND_URL = _frontend_url_env or "http://localhost:3000"

if DEBUG:
    CORS_ALLOWED_ORIGINS = _csv_env_list(
        "CORS_ALLOWED_ORIGINS",
        ["http://localhost:3000", "http://127.0.0.1:3000"],
    )
else:
    # In production, CORS must be explicit.
    CORS_ALLOWED_ORIGINS = _csv_env_list("CORS_ALLOWED_ORIGINS", [])

if _frontend_url_env and _frontend_url_env not in CORS_ALLOWED_ORIGINS:
    CORS_ALLOWED_ORIGINS.append(_frontend_url_env)

_cors_origin_regexes = _csv_env_list("CORS_ALLOWED_ORIGIN_REGEXES", [])
if _cors_origin_regexes:
    CORS_ALLOWED_ORIGIN_REGEXES = _cors_origin_regexes
elif DEBUG:
    CORS_ALLOWED_ORIGIN_REGEXES = [r"^https:\/\/.*\.vercel\.app$"]
else:
    CORS_ALLOWED_ORIGIN_REGEXES = []

CORS_ALLOW_ALL_ORIGINS = os.environ.get("CORS_ALLOW_ALL_ORIGINS", "false").lower() == "true"
CORS_ALLOW_CREDENTIALS = True

_csrf_trusted_from_env = _csv_env_list("CSRF_TRUSTED_ORIGINS", [])
CSRF_TRUSTED_ORIGINS = _csrf_trusted_from_env or list(CORS_ALLOWED_ORIGINS)

from corsheaders.defaults import default_headers
CORS_ALLOW_HEADERS = list(default_headers) + [
    "x-tenant-id",
]

# REST Framework Configuration - Allow public access for demo
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'users.authentication.TenantAwareJWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/day',
        'user': '1000/day',
        'auth_login': os.environ.get('THROTTLE_AUTH_LOGIN', '20/min'),
        'auth_refresh': os.environ.get('THROTTLE_AUTH_REFRESH', '40/min'),
        'auth_register': os.environ.get('THROTTLE_AUTH_REGISTER', '5/hour'),
        'auth_password_reset': os.environ.get('THROTTLE_AUTH_PASSWORD_RESET', '5/hour'),
        'auth_password_reset_confirm': os.environ.get('THROTTLE_AUTH_PASSWORD_RESET_CONFIRM', '10/hour'),
    },
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'EXCEPTION_HANDLER': 'core.exceptions.api_exception_handler',
    'DEFAULT_SCHEMA_CLASS': 'core.schema.UniqueOperationIdAutoSchema',
}

_jwt_default_access_minutes = int(os.environ.get("JWT_ACCESS_MINUTES_DEFAULT", "60"))
_jwt_default_refresh_days = int(os.environ.get("JWT_REFRESH_DAYS_DEFAULT", "7"))

SIMPLE_JWT = {
    'USER_ID_FIELD': 'user_id',
    'USER_ID_CLAIM': 'user_id',
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=_jwt_default_access_minutes),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=_jwt_default_refresh_days),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

JWT_ROLE_TOKEN_LIFETIMES = {
    # High-risk roles get shorter lifetimes.
    "saas_admin": {
        "access": timedelta(minutes=int(os.environ.get("JWT_ACCESS_MINUTES_SAAS_ADMIN", "15"))),
        "refresh": timedelta(days=int(os.environ.get("JWT_REFRESH_DAYS_SAAS_ADMIN", "1"))),
    },
    "admin": {
        "access": timedelta(minutes=int(os.environ.get("JWT_ACCESS_MINUTES_ADMIN", "20"))),
        "refresh": timedelta(days=int(os.environ.get("JWT_REFRESH_DAYS_ADMIN", "2"))),
    },
    "staff": {
        "access": timedelta(minutes=int(os.environ.get("JWT_ACCESS_MINUTES_STAFF", "30"))),
        "refresh": timedelta(days=int(os.environ.get("JWT_REFRESH_DAYS_STAFF", "3"))),
    },
    "teacher": {
        "access": timedelta(minutes=int(os.environ.get("JWT_ACCESS_MINUTES_TEACHER", "45"))),
        "refresh": timedelta(days=int(os.environ.get("JWT_REFRESH_DAYS_TEACHER", "5"))),
    },
    "parent": {
        "access": timedelta(minutes=int(os.environ.get("JWT_ACCESS_MINUTES_PARENT", "60"))),
        "refresh": timedelta(days=int(os.environ.get("JWT_REFRESH_DAYS_PARENT", "7"))),
    },
    "student": {
        "access": timedelta(minutes=int(os.environ.get("JWT_ACCESS_MINUTES_STUDENT", "60"))),
        "refresh": timedelta(days=int(os.environ.get("JWT_REFRESH_DAYS_STUDENT", "7"))),
    },
}

JWT_STRICT_REFRESH_ROTATION = os.environ.get("JWT_STRICT_REFRESH_ROTATION", "true").lower() == "true"

DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", "support@elearning.dev")

# Tenant trust policy:
# - dev_only (default): allow x-tenant-id only when DEBUG=True
# - always: trust x-tenant-id in all envs (not recommended)
# - never: ignore x-tenant-id in all envs
TENANT_HEADER_TRUST_MODE = os.environ.get("TENANT_HEADER_TRUST_MODE", "dev_only").lower()

# Security headers baseline
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = "DENY"
SECURE_REFERRER_POLICY = "same-origin"
SECURE_CROSS_ORIGIN_OPENER_POLICY = "same-origin"

_csp_connect_src = ["'self'"]
for _origin in CORS_ALLOWED_ORIGINS:
    if _origin and _origin not in _csp_connect_src:
        _csp_connect_src.append(_origin)
for _origin in _csv_env_list("CSP_CONNECT_SRC_EXTRA", []):
    if _origin and _origin not in _csp_connect_src:
        _csp_connect_src.append(_origin)

SECURITY_CSP_REPORT_ONLY = os.environ.get("CSP_REPORT_ONLY", "false").lower() == "true"
SECURITY_CSP_POLICY = {
    "default-src": ("'self'",),
    "base-uri": ("'self'",),
    "frame-ancestors": ("'none'",),
    "form-action": ("'self'",),
    "object-src": ("'none'",),
    # Keep Django admin and app shells functional while still setting a baseline.
    "script-src": ("'self'", "'unsafe-inline'"),
    "style-src": ("'self'", "'unsafe-inline'"),
    "img-src": ("'self'", "data:", "blob:", "https:"),
    "font-src": ("'self'", "data:"),
    "connect-src": tuple(_csp_connect_src),
}
SECURITY_PERMISSIONS_POLICY = os.environ.get(
    "SECURITY_PERMISSIONS_POLICY",
    "camera=(), microphone=(), geolocation=()",
)

if DEBUG:
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    SECURE_SSL_REDIRECT = False
    SECURE_HSTS_SECONDS = 0
else:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_SSL_REDIRECT = os.environ.get("SECURE_SSL_REDIRECT", "false").lower() == "true"
    SECURE_HSTS_SECONDS = int(os.environ.get("SECURE_HSTS_SECONDS", str(60 * 60 * 24 * 30)))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = os.environ.get("SECURE_HSTS_INCLUDE_SUBDOMAINS", "true").lower() == "true"
    SECURE_HSTS_PRELOAD = os.environ.get("SECURE_HSTS_PRELOAD", "false").lower() == "true"

if os.environ.get("SECURE_PROXY_SSL_HEADER"):
    # expected format: HTTP_X_FORWARDED_PROTO,https
    _proxy_parts = [p.strip() for p in os.environ["SECURE_PROXY_SSL_HEADER"].split(",", 1)]
    if len(_proxy_parts) == 2 and _proxy_parts[0] and _proxy_parts[1]:
        SECURE_PROXY_SSL_HEADER = (_proxy_parts[0], _proxy_parts[1])

# Caching Configuration
if 'REDIS_URL' in os.environ:
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": os.environ["REDIS_URL"],
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
            }
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "unique-snowflake",
        }
    }

# Audit Log Configuration
AUDITLOG_LOGENTRY_MODEL = 'auditlog.LogEntry'
AUDITLOG_DISABLE_REMOTE_ADDR = False
AUDITLOG_CID_GETTER = None
AUDITLOG_CID_HEADER = None

# Structured logging with request and tenant correlation
LOG_LEVEL = os.environ.get("LOG_LEVEL", "INFO").upper()
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "filters": {
        "request_context": {
            "()": "core.logging_context.RequestContextLogFilter",
        },
    },
    "formatters": {
        "structured": {
            "format": (
                "%(asctime)s level=%(levelname)s logger=%(name)s "
                "trace_id=%(request_id)s tenant_schema=%(tenant_schema)s tenant_id=%(tenant_id)s "
                "message=%(message)s"
            ),
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "structured",
            "filters": ["request_context"],
        },
    },
    "root": {
        "handlers": ["console"],
        "level": LOG_LEVEL,
    },
}

# Sentry integration (optional; enabled only when package + DSN are available)
SENTRY_DSN = (os.environ.get("SENTRY_DSN", "") or "").strip()
if SENTRY_DSN:
    try:
        import sentry_sdk
        from sentry_sdk.integrations.django import DjangoIntegration

        sentry_sdk.init(
            dsn=SENTRY_DSN,
            environment=os.environ.get("SENTRY_ENVIRONMENT", "production"),
            traces_sample_rate=float(os.environ.get("SENTRY_TRACES_SAMPLE_RATE", "0.05")),
            send_default_pii=False,
            integrations=[DjangoIntegration()],
        )
    except Exception as sentry_error:
        print(f"Sentry initialization skipped: {sentry_error}", file=sys.stderr)
