# Generated by Django 5.2.9 on 2026-02-04 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0012_add_notice_fields"),
        ("gamification", "0002_gamificationprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamificationprofile",
            name="is_public",
            field=models.BooleanField(default=True, help_text="Show in leaderboards"),
        ),
        migrations.AlterField(
            model_name="gamificationprofile",
            name="student",
            field=models.OneToOneField(
                db_constraint=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gamification_profile",
                to="academic.student",
            ),
        ),
        migrations.AlterField(
            model_name="pointtransaction",
            name="student",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="points",
                to="academic.student",
            ),
        ),
        migrations.AlterField(
            model_name="studentbadge",
            name="student",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="badges",
                to="academic.student",
            ),
        ),
    ]
