# Generated by Django 5.2.9 on 2026-02-26 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraccount",
            name="is_2fa_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="useraccount",
            name="two_factor_secret",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
