# Generated by Django 5.2.9 on 2026-03-01 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_add_2fa_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraccount",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "Student"),
                    ("teacher", "Teacher"),
                    ("parent", "Parent"),
                    ("admin", "Admin"),
                    ("staff", "Staff"),
                    ("saas_admin", "SaaS Admin"),
                ],
                default="student",
                max_length=20,
            ),
        ),
    ]
