# Generated by Django 4.2 on 2026-01-17 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_useraccount_address_useraccount_bio_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraccount",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "Student"),
                    ("teacher", "Teacher"),
                    ("parent", "Parent"),
                    ("admin", "Admin"),
                    ("saas_admin", "SaaS Admin"),
                ],
                default="student",
                max_length=20,
            ),
        ),
    ]
