# Generated by Django 5.2.9 on 2026-03-01 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_useraccount_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraccount",
            name="first_name",
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="useraccount",
            name="last_name",
            field=models.CharField(db_index=True, max_length=150),
        ),
    ]
