# Generated by Django 4.2 on 2026-01-17 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_tenant_db_alias_tenant_db_name_tenant_domain_url"),
        ("users", "0003_alter_useraccount_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraccount",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.tenant",
            ),
        ),
    ]
