# Generated by Django 5.2.9 on 2026-03-05 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("core", "0005_globalsettings_ai_provider_fields"),
        ("users", "0004_alter_useraccount_first_name_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="useraccount",
            index=models.Index(fields=["tenant", "role"], name="users_tenant_role_idx"),
        ),
        migrations.AddIndex(
            model_name="useraccount",
            index=models.Index(
                fields=["tenant", "is_active"], name="users_tenant_active_idx"
            ),
        ),
    ]
