# Generated by Django 5.2.9 on 2026-01-19 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_useraccount_tenant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraccount",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
