# Generated by Django 5.2.9 on 2026-04-09 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_useraccount_saas_staff_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraccount",
            name="expo_push_token",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
