# Generated by Django 4.2 on 2026-01-20 01:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AcademicClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. Grade 1, Class 10", max_length=50, unique=True
                    ),
                ),
                (
                    "order",
                    models.IntegerField(default=0, help_text="For sorting purposes"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Academic Classes",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="AcademicYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. 2025-2026", max_length=20, unique=True
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "is_current",
                    models.BooleanField(
                        default=False, help_text="Set this as the active academic year"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Notice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Title of the notice", max_length=200),
                ),
                ("content", models.TextField()),
                (
                    "target_audience",
                    models.CharField(
                        choices=[
                            ("student", "Specific Student"),
                            ("class", "Specific Class"),
                            ("school", "Whole School"),
                        ],
                        default="school",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Parent",
            fields=[
                (
                    "parent_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="e.g. A, B, Red, Blue", max_length=20),
                ),
                ("capacity", models.IntegerField(default=40)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "student_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "learning_style",
                    models.CharField(
                        choices=[
                            ("visual", "Visual (Video)"),
                            ("reading", "Reading (Text)"),
                            ("practice", "Practice (Quiz)"),
                        ],
                        default="visual",
                        max_length=20,
                    ),
                ),
                (
                    "daily_study_goal",
                    models.IntegerField(
                        default=30, help_text="Daily study goal in minutes"
                    ),
                ),
                (
                    "ai_explanation_level",
                    models.CharField(
                        choices=[
                            ("simple", "Simple"),
                            ("normal", "Normal"),
                            ("exam", "Exam-Oriented"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                ("language_preference", models.CharField(default="en", max_length=10)),
                ("current_streak", models.IntegerField(default=0)),
                ("total_minutes_learned", models.IntegerField(default=0)),
                (
                    "focus_score",
                    models.IntegerField(
                        default=85, help_text="AI-calculated focus score 0-100"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(blank=True, max_length=20, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "credits",
                    models.DecimalField(decimal_places=1, default=1.0, max_digits=4),
                ),
                ("is_elective", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "teacher_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "designation",
                    models.CharField(
                        choices=[
                            ("subject_teacher", "Subject Teacher"),
                            ("class_teacher", "Class Teacher"),
                            ("program_director", "Program Director"),
                        ],
                        default="subject_teacher",
                        max_length=50,
                    ),
                ),
                (
                    "assigned_classes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="assigned_teachers",
                        to="academic.academicclass",
                    ),
                ),
            ],
        ),
    ]
