# Generated by Django 5.2.9 on 2026-02-21 06:17

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AcademicClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. Grade 1, Class 10", max_length=50, unique=True
                    ),
                ),
                (
                    "order",
                    models.IntegerField(default=0, help_text="For sorting purposes"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Academic Classes",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="AcademicYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. 2025-2026", max_length=20, unique=True
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "is_current",
                    models.BooleanField(
                        default=False, help_text="Set this as the active academic year"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Assessment",
            fields=[
                (
                    "assessment_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(default="Assessment", max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("quiz", "Quiz"),
                            ("exam", "Exam"),
                            ("assignment", "Assignment"),
                        ],
                        default="quiz",
                        max_length=50,
                    ),
                ),
                ("total_marks", models.IntegerField()),
                ("passing_marks", models.IntegerField(default=40)),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("due_date", models.DateTimeField(blank=True, null=True)),
                ("duration_minutes", models.IntegerField(default=60)),
                (
                    "blooms_level",
                    models.CharField(
                        choices=[
                            ("remember", "Remember"),
                            ("understand", "Understand"),
                            ("apply", "Apply"),
                            ("analyze", "Analyze"),
                            ("evaluate", "Evaluate"),
                            ("create", "Create"),
                        ],
                        default="remember",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                ("attendance_id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "Present"),
                            ("absent", "Absent"),
                            ("late", "Late"),
                            ("excused", "Excused"),
                        ],
                        default="present",
                        max_length=20,
                    ),
                ),
                ("remarks", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Chapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_published", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="Parent",
            fields=[
                (
                    "parent_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "question_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("text", models.TextField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("mcq", "Multiple Choice"),
                            ("short_answer", "Short Answer"),
                            ("long_answer", "Long Answer/Essay"),
                            ("code", "Code Snippet"),
                        ],
                        default="mcq",
                        max_length=50,
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True, default=list, help_text="Tags for categorization"
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "options",
                    models.JSONField(
                        blank=True, default=list, help_text="List of options for MCQ"
                    ),
                ),
                (
                    "correct_answer",
                    models.TextField(
                        blank=True, help_text="Correct answer key or text", null=True
                    ),
                ),
                ("points", models.IntegerField(default=1)),
                ("order", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Result",
            fields=[
                (
                    "result_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("score", models.IntegerField()),
                ("time_taken_minutes", models.IntegerField(default=0)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ai_feedback",
                    models.TextField(
                        blank=True,
                        help_text="AI generated feedback on performance",
                        null=True,
                    ),
                ),
                ("teacher_feedback", models.TextField(blank=True, null=True)),
                ("answers_data", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="e.g. A, B, Red, Blue", max_length=20),
                ),
                ("capacity", models.IntegerField(default=40)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "student_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "learning_style",
                    models.CharField(
                        choices=[
                            ("visual", "Visual (Video)"),
                            ("reading", "Reading (Text)"),
                            ("practice", "Practice (Quiz)"),
                        ],
                        default="visual",
                        max_length=20,
                    ),
                ),
                (
                    "daily_study_goal",
                    models.IntegerField(
                        default=30, help_text="Daily study goal in minutes"
                    ),
                ),
                (
                    "ai_explanation_level",
                    models.CharField(
                        choices=[
                            ("simple", "Simple"),
                            ("normal", "Normal"),
                            ("exam", "Exam-Oriented"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                ("language_preference", models.CharField(default="en", max_length=10)),
                ("current_streak", models.IntegerField(default=0)),
                ("total_minutes_learned", models.IntegerField(default=0)),
                (
                    "focus_score",
                    models.IntegerField(
                        default=85, help_text="AI-calculated focus score 0-100"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(blank=True, max_length=20, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "credits",
                    models.DecimalField(decimal_places=1, default=1.0, max_digits=4),
                ),
                ("is_elective", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "submission_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True, help_text="Text content or essay", null=True
                    ),
                ),
                (
                    "file_url",
                    models.CharField(
                        blank=True,
                        help_text="URL to uploaded file",
                        max_length=500,
                        null=True,
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("graded", "Graded"),
                            ("late", "Submitted Late"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("is_graded", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "teacher_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "designation",
                    models.CharField(
                        choices=[
                            ("subject_teacher", "Subject Teacher"),
                            ("class_teacher", "Class Teacher"),
                            ("program_director", "Program Director"),
                        ],
                        default="subject_teacher",
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Timetable",
            fields=[
                ("timetable_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "day_of_week",
                    models.CharField(
                        choices=[
                            ("Monday", "Monday"),
                            ("Tuesday", "Tuesday"),
                            ("Wednesday", "Wednesday"),
                            ("Thursday", "Thursday"),
                            ("Friday", "Friday"),
                            ("Saturday", "Saturday"),
                            ("Sunday", "Sunday"),
                        ],
                        max_length=20,
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("subject_name", models.CharField(max_length=100)),
                ("room_number", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "ordering": ["day_of_week", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "exam_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("hall_ticket_prefix", models.CharField(default="EXAM", max_length=20)),
                (
                    "exam_center",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("seating_capacity", models.IntegerField(default=30)),
                ("instructions", models.TextField(blank=True, null=True)),
                ("is_published", models.BooleanField(default=False)),
                ("results_released", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assessment",
                    models.OneToOneField(
                        limit_choices_to={"type": "exam"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_details",
                        to="academic.assessment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExamSeating",
            fields=[
                (
                    "seating_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("hall_ticket_number", models.CharField(max_length=50, unique=True)),
                ("room_number", models.CharField(max_length=50)),
                ("seat_number", models.CharField(max_length=50)),
                (
                    "attendance_status",
                    models.CharField(
                        choices=[
                            ("present", "Present"),
                            ("absent", "Absent"),
                            ("late", "Late"),
                        ],
                        default="present",
                        max_length=20,
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seating_arrangements",
                        to="academic.exam",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("text", "Text/Article"),
                            ("video", "Video"),
                            ("interactive", "Interactive"),
                            ("quiz", "Quiz/Assessment"),
                        ],
                        default="text",
                        max_length=20,
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True, help_text="Rich text content (HTML/Markdown)"
                    ),
                ),
                (
                    "video_url",
                    models.URLField(
                        blank=True,
                        help_text="Link to video lecture (YouTube/Vimeo)",
                        null=True,
                    ),
                ),
                (
                    "interactive_data",
                    models.JSONField(
                        blank=True,
                        help_text="JSON payload for interactive content",
                        null=True,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_published", models.BooleanField(default=False)),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        default=45, help_text="Estimated duration"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assessment",
                    models.ForeignKey(
                        blank=True,
                        help_text="Linked Quiz/Assessment",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="linked_lessons",
                        to="academic.assessment",
                    ),
                ),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="academic.chapter",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="LessonMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="lesson_materials/"
                    ),
                ),
                ("link", models.URLField(blank=True, null=True)),
                (
                    "material_type",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF Document"),
                            ("image", "Image"),
                            ("video", "Video File"),
                            ("link", "External Link"),
                            ("other", "Other File"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materials",
                        to="academic.lesson",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LessonProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("completed", models.BooleanField(default=False)),
                ("xp_awarded", models.BooleanField(default=False)),
                ("last_accessed", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progresses",
                        to="academic.lesson",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Lesson Progresses",
            },
        ),
        migrations.CreateModel(
            name="Notice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("category", models.CharField(default="General", max_length=50)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                (
                    "target_audience",
                    models.CharField(
                        choices=[
                            ("school", "Whole School"),
                            ("class", "Specific Class"),
                            ("student", "Specific Student"),
                        ],
                        default="school",
                        max_length=20,
                    ),
                ),
                ("published_date", models.DateTimeField(auto_now_add=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        help_text="Upload PDF or Image",
                        null=True,
                        upload_to="notices/",
                    ),
                ),
                (
                    "target_class",
                    models.ForeignKey(
                        blank=True,
                        help_text="Required if audience is 'Specific Class'",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="academic.academicclass",
                    ),
                ),
            ],
            options={
                "ordering": ["-published_date"],
            },
        ),
    ]
