# Generated by Django 4.2 on 2026-01-16 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="ai_explanation_level",
            field=models.CharField(
                choices=[
                    ("simple", "Simple"),
                    ("normal", "Normal"),
                    ("exam", "Exam-Oriented"),
                ],
                default="normal",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="current_streak",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="student",
            name="daily_study_goal",
            field=models.IntegerField(
                default=30, help_text="Daily study goal in minutes"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="focus_score",
            field=models.IntegerField(
                default=85, help_text="AI-calculated focus score 0-100"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="language_preference",
            field=models.CharField(default="en", max_length=10),
        ),
        migrations.AddField(
            model_name="student",
            name="learning_style",
            field=models.CharField(
                choices=[
                    ("visual", "Visual (Video)"),
                    ("reading", "Reading (Text)"),
                    ("practice", "Practice (Quiz)"),
                ],
                default="visual",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="total_minutes_learned",
            field=models.IntegerField(default=0),
        ),
    ]
