# Generated by Django 4.2 on 2026-01-16 10:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0003_alter_result_options_assessment_blooms_level_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessment",
            name="due_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "submission_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True, help_text="Text content or essay", null=True
                    ),
                ),
                (
                    "file_url",
                    models.CharField(
                        blank=True,
                        help_text="URL to uploaded file",
                        max_length=500,
                        null=True,
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("graded", "Graded"),
                            ("late", "Submitted Late"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("is_graded", models.BooleanField(default=False)),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="academic.assessment",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="academic.student",
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_at"],
                "unique_together": {("assessment", "student")},
            },
        ),
    ]
