# Generated by Django 4.2 on 2026-01-16 10:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0004_assessment_due_date_submission"),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "question_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("text", models.TextField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("mcq", "Multiple Choice"),
                            ("short_answer", "Short Answer"),
                            ("long_answer", "Long Answer/Essay"),
                            ("code", "Code Snippet"),
                        ],
                        default="mcq",
                        max_length=50,
                    ),
                ),
                (
                    "options",
                    models.JSONField(
                        blank=True, default=list, help_text="List of options for MCQ"
                    ),
                ),
                (
                    "correct_answer",
                    models.TextField(
                        blank=True, help_text="Correct answer key or text", null=True
                    ),
                ),
                ("points", models.IntegerField(default=1)),
                ("order", models.IntegerField(default=0)),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="academic.assessment",
                    ),
                ),
            ],
        ),
    ]
