# Generated by Django 4.2 on 2026-01-16 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0005_question"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="courses_taught",
                to="academic.teacher",
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="assigned_classes",
            field=models.ManyToManyField(
                blank=True,
                related_name="assigned_teachers",
                to="academic.academicclass",
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="designation",
            field=models.CharField(
                choices=[
                    ("subject_teacher", "Subject Teacher"),
                    ("class_teacher", "Class Teacher"),
                    ("program_director", "Program Director"),
                ],
                default="subject_teacher",
                max_length=50,
            ),
        ),
    ]
