# Generated by Django 5.2.9 on 2026-03-04 12:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0005_timetable_workflow_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="timetable",
            index=models.Index(
                fields=["academic_class", "day_of_week", "start_time"],
                name="tt_class_day_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="timetable",
            index=models.Index(
                fields=["academic_class", "status", "entry_type"],
                name="tt_class_status_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="timetable",
            index=models.Index(
                fields=["teacher", "day_of_week", "start_time"],
                name="tt_teacher_day_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="timetable",
            index=models.Index(
                fields=["created_by", "status"], name="tt_creator_status_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="timetable",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_time__gt", models.F("start_time"))),
                name="tt_end_after_start_chk",
            ),
        ),
    ]
