# Generated by Django 4.2 on 2026-01-17 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0004_tenant_db_alias_tenant_db_name_tenant_domain_url"),
        ("academic", "0006_course_teacher_teacher_assigned_classes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="academicclass",
            name="tenant",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classes",
                to="core.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="user",
            field=models.OneToOneField(
                db_constraint=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
