# Generated by Django 5.2.9 on 2026-03-05 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def backfill_academic_year_on_existing_data(apps, schema_editor):
    AcademicYear = apps.get_model("academic", "AcademicYear")
    Subject = apps.get_model("academic", "Subject")
    Timetable = apps.get_model("academic", "Timetable")
    Assessment = apps.get_model("academic", "Assessment")

    current_year = AcademicYear.objects.filter(is_current=True).order_by("-start_date").first()
    if current_year is None:
        today = timezone.localdate()
        if (today.month, today.day) >= (4, 1):
            start_year = today.year
        else:
            start_year = today.year - 1
        current_year, _ = AcademicYear.objects.get_or_create(
            name=f"{start_year}-{start_year + 1}",
            defaults={
                "start_date": today.replace(year=start_year, month=4, day=1),
                "end_date": today.replace(year=start_year + 1, month=3, day=31),
                "is_current": True,
            },
        )
        if not current_year.is_current:
            AcademicYear.objects.exclude(pk=current_year.pk).update(is_current=False)
            current_year.is_current = True
            current_year.save(update_fields=["is_current"])

    Subject.objects.filter(academic_year__isnull=True).update(academic_year=current_year)
    Timetable.objects.filter(academic_year__isnull=True).update(academic_year=current_year)
    Assessment.objects.filter(academic_year__isnull=True).update(academic_year=current_year)


def noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0007_lessonprogress_video_tracking"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="subject",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="assessment",
            name="academic_year",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assessments",
                to="academic.academicyear",
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="is_final_assessment",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="assessment",
            name="results_published",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="assessment",
            name="results_published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subject",
            name="academic_year",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subjects",
                to="academic.academicyear",
            ),
        ),
        migrations.AddField(
            model_name="timetable",
            name="academic_year",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="timetable_entries",
                to="academic.academicyear",
            ),
        ),
        migrations.RunPython(backfill_academic_year_on_existing_data, noop_reverse),
        migrations.AlterUniqueTogether(
            name="subject",
            unique_together={("name", "academic_class", "academic_year")},
        ),
        migrations.AddIndex(
            model_name="timetable",
            index=models.Index(
                fields=["academic_year", "academic_class", "day_of_week", "start_time"],
                name="tt_year_class_day_idx",
            ),
        ),
    ]
