# Generated by Django 5.2.10 on 2026-01-18 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0008_notice_timetable_attendance"),
    ]

    operations = [
        migrations.AddField(
            model_name="notice",
            name="target_student",
            field=models.ForeignKey(
                blank=True,
                help_text="Required if audience is 'Specific Student'",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="academic.student",
            ),
        ),
        migrations.AlterField(
            model_name="notice",
            name="target_audience",
            field=models.CharField(
                choices=[
                    ("school", "Whole School"),
                    ("class", "Specific Class"),
                    ("student", "Specific Student"),
                ],
                default="school",
                max_length=20,
            ),
        ),
    ]
