# Generated by Django 5.2.9 on 2026-03-05 07:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0008_alter_subject_unique_together_and_more"),
        ("core", "0005_globalsettings_ai_provider_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdmissionEnquiry",
            fields=[
                (
                    "enquiry_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(blank=True, default="", max_length=150)),
                (
                    "guardian_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone_number", models.CharField(max_length=20)),
                (
                    "desired_section_name",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("contacted", "Contacted"),
                            ("interested", "Interested"),
                            ("application_started", "Application Started"),
                            ("converted", "Converted"),
                            ("closed", "Closed"),
                        ],
                        default="new",
                        max_length=30,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("walk_in", "Walk In"),
                            ("website", "Website"),
                            ("referral", "Referral"),
                            ("social", "Social Media"),
                            ("phone", "Phone"),
                            ("other", "Other"),
                        ],
                        default="walk_in",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("follow_up_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "converted_student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admission_conversions",
                        to="academic.student",
                    ),
                ),
                (
                    "desired_class",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admission_enquiries",
                        to="academic.academicclass",
                    ),
                ),
                (
                    "handled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="handled_admission_enquiries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admission_enquiries",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "status"], name="admission_tenant_status_idx"
                    ),
                    models.Index(
                        fields=["tenant", "created_at"],
                        name="admission_tenant_created_idx",
                    ),
                ],
            },
        ),
    ]
