# Generated by Django 5.2.10 on 2026-01-25 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0009_notice_tenant"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessment",
            name="section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assessments",
                to="academic.section",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="difficulty",
            field=models.CharField(
                choices=[("easy", "Easy"), ("medium", "Medium"), ("hard", "Hard")],
                default="medium",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="tags",
            field=models.JSONField(
                blank=True, default=list, help_text="Tags for categorization"
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="assessment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="academic.assessment",
            ),
        ),
    ]
