# Generated by Django 5.2.10 on 2026-01-30 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "academic",
            "0010_assessment_section_question_difficulty_question_tags_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notice",
            options={"ordering": ["-published_date"]},
        ),
        migrations.RenameField(
            model_name="notice",
            old_name="created_at",
            new_name="published_date",
        ),

        migrations.RemoveField(
            model_name="notice",
            name="tenant",
        ),
        migrations.AddField(
            model_name="lesson",
            name="assessment",
            field=models.ForeignKey(
                blank=True,
                help_text="Linked Quiz/Assessment",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="linked_lessons",
                to="academic.assessment",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="content_type",
            field=models.CharField(
                choices=[
                    ("text", "Text/Article"),
                    ("video", "Video"),
                    ("interactive", "Interactive"),
                    ("quiz", "Quiz/Assessment"),
                ],
                default="text",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="interactive_data",
            field=models.JSONField(
                blank=True, help_text="JSON payload for interactive content", null=True
            ),
        ),

        migrations.AlterField(
            model_name="notice",
            name="target_audience",
            field=models.CharField(
                choices=[
                    ("school", "Whole School"),
                    ("class", "Specific Class"),
                    ("student", "Specific Student"),
                ],
                default="school",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="notice",
            name="target_class",
            field=models.ForeignKey(
                blank=True,
                help_text="Required if audience is 'Specific Class'",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="academic.academicclass",
            ),
        ),
        migrations.AlterField(
            model_name="notice",
            name="target_student",
            field=models.ForeignKey(
                blank=True,
                help_text="Required if audience is 'Specific Student'",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="academic.student",
            ),
        ),
        migrations.AlterField(
            model_name="notice",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
