# Generated by Django 5.2.9 on 2026-03-05

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0010_studentpromotiondecision"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="studentpromotiondecision",
            name="decision_reason",
            field=models.TextField(default="Legacy decision reason (migrated)"),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="StudentPromotionDecisionHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "history_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("promote", "Promote"),
                            ("hold", "Hold"),
                            ("override", "Override"),
                            ("clear", "Clear"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "previous_decision",
                    models.CharField(
                        blank=True,
                        choices=[("promote", "Promote"), ("hold", "Hold")],
                        max_length=16,
                        null=True,
                    ),
                ),
                (
                    "new_decision",
                    models.CharField(
                        blank=True,
                        choices=[("promote", "Promote"), ("hold", "Hold")],
                        max_length=16,
                        null=True,
                    ),
                ),
                ("decision_reason", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promotion_decision_history",
                        to="academic.assessment",
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="student_promotion_decision_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promotion_decision_history",
                        to="academic.student",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
