# Generated by Django 5.2.9 on 2026-02-04 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0012_add_notice_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="lessonprogress",
            name="xp_awarded",
            field=models.BooleanField(default=False),
        ),
    ]
