# Generated by Django 5.2.9 on 2026-03-05 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0012_assessmentresultpublicationaudit"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="attendance",
            index=models.Index(
                fields=["student", "date"], name="acad_att_student_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendance",
            index=models.Index(
                fields=["subject", "date"], name="acad_att_subject_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["academic_class", "section"],
                name="acad_stu_class_sec_idx",
            ),
        ),
    ]
