# Generated by Django 5.2.9 on 2026-03-05 13:34

from django.db import migrations, models

import academic.models.lesson
import academic.models.notice


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0013_attendance_student_indexes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lessonmaterial",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=academic.models.lesson.lesson_material_upload_to,
            ),
        ),
        migrations.AlterField(
            model_name="notice",
            name="attachment",
            field=models.FileField(
                blank=True,
                help_text="Upload PDF or Image",
                null=True,
                upload_to=academic.models.notice.notice_attachment_upload_to,
            ),
        ),
    ]
