# Generated by Django 5.2.9 on 2026-02-04 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0013_lessonprogress_xp_awarded"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
