# Generated by Django 5.2.9 on 2026-02-05 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0014_subject_is_active"),
        ("core", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notice",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notices",
                to="core.tenant",
            ),
        ),
    ]
