# Generated by Django 5.2.9 on 2026-02-05 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0014_subject_is_active"),
        ("core", "0002_initial"),
    ]

    operations = [
        # Duplicate operation removed
    ]
