# Generated by Django 5.2.9 on 2026-02-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0015_notice_tenant"),
    ]

    operations = [
        migrations.AddField(
            model_name="chapter",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
    ]
