# Generated by Django 5.2.9 on 2026-02-09 02:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0018_notice_tenant"),
    ]

    operations = [
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "exam_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("hall_ticket_prefix", models.CharField(default="EXAM", max_length=20)),
                (
                    "exam_center",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("seating_capacity", models.IntegerField(default=30)),
                ("instructions", models.TextField(blank=True, null=True)),
                ("is_published", models.BooleanField(default=False)),
                ("results_released", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assessment",
                    models.OneToOneField(
                        limit_choices_to={"type": "exam"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_details",
                        to="academic.assessment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExamSeating",
            fields=[
                (
                    "seating_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("hall_ticket_number", models.CharField(max_length=50, unique=True)),
                ("room_number", models.CharField(max_length=50)),
                ("seat_number", models.CharField(max_length=50)),
                (
                    "attendance_status",
                    models.CharField(
                        choices=[
                            ("present", "Present"),
                            ("absent", "Absent"),
                            ("late", "Late"),
                        ],
                        default="present",
                        max_length=20,
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seating_arrangements",
                        to="academic.exam",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_seating",
                        to="academic.student",
                    ),
                ),
            ],
            options={
                "unique_together": {("exam", "student")},
            },
        ),
    ]
