# Generated by Django 5.2.9 on 2026-03-15 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0019_alter_studentdocument_document_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="video_transcript",
            field=models.TextField(
                blank=True,
                help_text="Auto-generated or manually entered transcript for video lessons",
                null=True,
            ),
        ),
    ]
