# Generated by Django 5.2.9 on 2026-03-22 01:44

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0020_lesson_video_transcript"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LiveSession",
            fields=[
                (
                    "session_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("jitsi_room", models.CharField(max_length=200, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("live", "Live"), ("ended", "Ended")],
                        default="live",
                        max_length=10,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "started_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="started_live_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "timetable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="live_sessions",
                        to="academic.timetable",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["timetable", "status"], name="ls_timetable_status_idx"
                    ),
                    models.Index(
                        fields=["status", "started_at"], name="ls_status_started_idx"
                    ),
                ],
            },
        ),
    ]
