# Generated by Django 5.2.9 on 2026-06-11 02:36

from django.db import migrations, models

import academic.models.lesson
import academic.models.notice
import core.upload_validation


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0022_noticeread"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lessonmaterial",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=academic.models.lesson.lesson_material_upload_to,
                validators=[
                    core.upload_validation.MaxFileSizeValidator(),
                    core.upload_validation.SafeFileContentValidator(
                        frozenset(
                            [
                                "csv",
                                "doc",
                                "docx",
                                "gif",
                                "jpeg",
                                "jpg",
                                "m4a",
                                "md",
                                "mp3",
                                "mp4",
                                "odp",
                                "ods",
                                "odt",
                                "pdf",
                                "png",
                                "ppt",
                                "pptx",
                                "txt",
                                "wav",
                                "webm",
                                "webp",
                                "xls",
                                "xlsx",
                                "zip",
                            ]
                        )
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="notice",
            name="attachment",
            field=models.FileField(
                blank=True,
                help_text="Upload PDF or Image",
                null=True,
                upload_to=academic.models.notice.notice_attachment_upload_to,
                validators=[
                    core.upload_validation.MaxFileSizeValidator(),
                    core.upload_validation.SafeFileContentValidator(
                        frozenset(["gif", "jpeg", "jpg", "pdf", "png", "webp"])
                    ),
                ],
            ),
        ),
    ]
