# Generated by Django 4.2 on 2026-01-20 01:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("action", models.CharField(max_length=255)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("details", models.JSONField(default=dict)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="GlobalSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(default="E-Learning SaaS", max_length=255),
                ),
                (
                    "maintenance_mode",
                    models.BooleanField(
                        default=False,
                        help_text="If active, only admins can access the site.",
                    ),
                ),
                (
                    "allow_registration",
                    models.BooleanField(
                        default=True, help_text="Allow new tenants/schools to register."
                    ),
                ),
                (
                    "support_email",
                    models.EmailField(default="support@example.com", max_length=254),
                ),
                (
                    "default_language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("es", "Spanish"),
                            ("fr", "French"),
                        ],
                        default="en",
                        max_length=10,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Global Settings",
                "verbose_name_plural": "Global Settings",
            },
        ),
        migrations.CreateModel(
            name="Tenant",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("subdomain", models.CharField(max_length=255, unique=True)),
                (
                    "domain",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("standard", "Standard"),
                            ("premium", "Premium"),
                            ("enterprise", "Enterprise"),
                        ],
                        default="standard",
                        max_length=20,
                    ),
                ),
                ("status", models.CharField(default="active", max_length=20)),
                (
                    "db_name",
                    models.CharField(
                        default="tenant_default.sqlite3",
                        help_text="Name of the database file or schema",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "db_alias",
                    models.CharField(
                        default="default_alias",
                        help_text="Django DB alias (e.g. 'default', 'tenant_1')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "domain_url",
                    models.CharField(
                        default="localhost",
                        help_text="Full domain (e.g. school.saas.com)",
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("address", models.TextField(blank=True, null=True)),
                (
                    "contact_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "contact_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("website", models.URLField(blank=True, null=True)),
                (
                    "current_academic_year",
                    models.CharField(default="2024-2025", max_length=20),
                ),
                ("established_year", models.IntegerField(blank=True, null=True)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="tenant_logos/"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
