# Generated by Django 4.2 on 2026-01-17 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_auditlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="GlobalSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(default="E-Learning SaaS", max_length=255),
                ),
                (
                    "maintenance_mode",
                    models.BooleanField(
                        default=False,
                        help_text="If active, only admins can access the site.",
                    ),
                ),
                (
                    "allow_registration",
                    models.BooleanField(
                        default=True, help_text="Allow new tenants/schools to register."
                    ),
                ),
                (
                    "support_email",
                    models.EmailField(default="support@example.com", max_length=254),
                ),
                (
                    "default_language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("es", "Spanish"),
                            ("fr", "French"),
                        ],
                        default="en",
                        max_length=10,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Global Settings",
                "verbose_name_plural": "Global Settings",
            },
        ),
    ]
