# Generated by Django 5.2.9 on 2026-02-27 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="features",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Stores active/inactive features for different roles, e.g., {'parents': {'view_attendance': True}}",
            ),
        ),
    ]
