# Generated by Django 5.2.9 on 2026-03-02 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_tenant_features"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="subdomain",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
