# Generated by Django 4.2 on 2026-01-17 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_globalsettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="db_alias",
            field=models.CharField(
                default="default_alias",
                help_text="Django DB alias (e.g. 'default', 'tenant_1')",
                max_length=100,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="db_name",
            field=models.CharField(
                default="tenant_default.sqlite3",
                help_text="Name of the database file or schema",
                max_length=100,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="domain_url",
            field=models.CharField(
                default="localhost",
                help_text="Full domain (e.g. school.saas.com)",
                max_length=255,
                unique=True,
            ),
        ),
    ]
