# Generated by Django 5.2.9 on 2026-03-02 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_tenant_subdomain"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalsettings",
            name="ai_api_key",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Secret API key for AI provider.",
            ),
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="ai_base_url",
            field=models.URLField(
                default="https://api.openai.com/v1",
                help_text="Base URL for OpenAI-compatible API provider.",
            ),
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="ai_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Enable or disable AI features globally.",
            ),
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="ai_model",
            field=models.CharField(
                default="gpt-3.5-turbo",
                help_text="Default AI model used across services.",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="ai_provider_name",
            field=models.CharField(
                default="OpenAI",
                help_text="Display name of the configured AI provider.",
                max_length=100,
            ),
        ),
    ]
