# Generated by Django 5.1.15 on 2026-01-17 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_tenant_db_alias_tenant_db_name_tenant_domain_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tenant",
            name="contact_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="tenant",
            name="contact_phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="tenant",
            name="current_academic_year",
            field=models.CharField(default="2024-2025", max_length=20),
        ),
        migrations.AddField(
            model_name="tenant",
            name="established_year",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tenant",
            name="website",
            field=models.URLField(blank=True, null=True),
        ),
    ]
