# Generated by Django 5.2.9 on 2026-03-05 13:34

import core.models.tenant
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_globalsettings_ai_provider_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenant",
            name="logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=core.models.tenant.tenant_logo_upload_to,
            ),
        ),
    ]
