# Generated by Django 5.2.9 on 2026-03-05

from django.db import migrations


def _enable_pgvector(apps, schema_editor):
    connection = schema_editor.connection
    if connection.vendor != "postgresql":
        return
    try:
        with connection.cursor() as cursor:
            cursor.execute("CREATE EXTENSION IF NOT EXISTS vector;")
    except Exception as exc:
        # Best-effort for managed databases where extension privileges are restricted.
        print(f"Warning: could not auto-enable pgvector extension: {exc}")


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("core", "0006_alter_tenant_logo"),
    ]

    operations = [
        migrations.RunPython(_enable_pgvector, migrations.RunPython.noop),
    ]
