# Generated by Django 5.2.9 on 2026-03-05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_enable_pgvector_extension"),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "job_id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("task_name", models.CharField(max_length=255)),
                (
                    "tenant_schema",
                    models.CharField(db_index=True, default="public", max_length=63),
                ),
                ("backend", models.CharField(default="sync", max_length=16)),
                (
                    "status",
                    models.CharField(db_index=True, default="queued", max_length=24),
                ),
                ("state", models.CharField(default="PENDING", max_length=32)),
                (
                    "submitted_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("result", models.JSONField(blank=True, null=True)),
                ("error", models.TextField(blank=True)),
                ("meta", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["-submitted_at"]},
        ),
    ]
