# Generated by Django 5.2.9 on 2026-05-06 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_backfill_tenant_projects_feature"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="feature_overrides",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Per-tenant overrides that win over plan entitlements, e.g., {'projects': False}.",
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="features",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Effective feature flags for this tenant. Computed from the plan + feature_overrides; do not edit directly.",
            ),
        ),
    ]
