# Generated by Django 5.2.9 on 2026-05-12 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_tenant_feature_overrides_alter_tenant_features"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="accountant_name",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="tenant",
            name="bill_prefix",
            field=models.CharField(
                default="BL",
                help_text='Prefix for sequential bill numbers, e.g. "BL" → BL-2082/83-00001.',
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="currency_code",
            field=models.CharField(
                default="NPR",
                help_text="ISO currency code shown on receipts. Default NPR for Nepali schools.",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="currency_symbol",
            field=models.CharField(
                default="Rs.",
                help_text='Short currency symbol on bills (e.g. "Rs.", "$").',
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="fiscal_year_bs",
            field=models.CharField(
                blank=True,
                default="",
                help_text='Current Bikram Sambat fiscal year, e.g. "2082/83". Used in bill numbering.',
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="pan_number",
            field=models.CharField(
                blank=True,
                default="",
                help_text="School PAN number printed on every tax invoice / receipt.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="principal_name",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="tenant",
            name="vat_number",
            field=models.CharField(
                blank=True,
                default="",
                help_text="VAT registration number (only if school is VAT-registered).",
                max_length=20,
            ),
        ),
    ]
