# Generated by Django 5.2.9 on 2026-06-11 02:36

from django.db import migrations, models

import core.models.tenant
import core.upload_validation


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_tenant_billing_identity_phase_a"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenant",
            name="logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=core.models.tenant.tenant_logo_upload_to,
                validators=[
                    core.upload_validation.MaxFileSizeValidator(),
                    core.upload_validation.SafeFileContentValidator(
                        frozenset(["gif", "jpeg", "jpg", "png", "webp"])
                    ),
                ],
            ),
        ),
    ]
